### ISSUE TITLE
LOADBG AUTO not playing

### ISSUE THREAD

**Issue by gizahNL** [CasparCG/server#1114] opened 2018-11-20 16:05 UTC
On 2.1 and earlier it is possible to schedule content to play automatically after the foreground item finishes playing by using `LOADBG CONTENTITEM AUTO`

Currently on 2.2 (git master Ubuntu 18.04) content does not start playing automatically.

Output from INFO command below, I notice at least one time counter that seems to have wrapped on layer 10 (which is the misbehaving layer).

```
201 INFO OK
<?xml version="1.0" encoding="utf-8"?>
<channel>
   <framerate>50</framerate>
   <framerate>1</framerate>
   <mixer>
      <audio>
         <volume>0</volume>
         <volume>0</volume>
         <volume>0</volume>
         <volume>0</volume>
         <volume>0</volume>
         <volume>0</volume>
         <volume>0</volume>
         <volume>0</volume>
      </audio>
   </mixer>
   <stage>
      <layer>
         <10>
            <background>
               <file>
                  <name>REDACTED/2900.mp4</name>
                  <path>/data/media//REDACTED/2900.mp4</path>
                  <stime>0</stime>
                  <stime>0</stime>
                  <streams>
                     <0>
                        <fps>0</fps>
                        <fps>0</fps>
                     </0>
                     <1>
                        <fps>25</fps>
                        <fps>1</fps>
                     </1>
                  </streams>
                  <time>0</time>
                  <time>0</time>
               </file>
               <loop>false</loop>
               <producer>transition</producer>
               <transition>
                  <frame>0</frame>
                  <frame>0</frame>
                  <type>cut</type>
               </transition>
            </background>
            <foreground>
               <file>
                  <name>REDACTED/1265.mp4</name>
                  <path>/data/media//REDACTED/1265.mp4</path>
                  <stime>3.04</stime>
                  <stime>3.0800000000000001</stime>
                  <streams>
                     <0>
                        <fps>25</fps>
                        <fps>1</fps>
                     </0>
                     <1>
                        <fps>0</fps>
                        <fps>0</fps>
                     </1>
                  </streams>
                  <time>3.04</time>
                  <time>-9223372036851.6992</time>
               </file>
               <loop>false</loop>
               <paused>false</paused>
               <producer>ffmpeg</producer>
            </foreground>
         </10>
         <15>
            <background>
               <producer>empty</producer>
            </background>
            <foreground>
               <file>
                  <path>file:///data/media/REDACTED/redacted.html?artist=MARTIN+GARRIX+FT+BONN&amp;title=High+On+Life</path>
               </file>
               <paused>false</paused>
               <producer>html</producer>
            </foreground>
         </15>
         <20>
            <background>
               <producer>empty</producer>
            </background>
            <foreground>
               <file>
                  <path>/data/media/REDACTED/fullscreen_wh.png</path>
               </file>
               <paused>false</paused>
               <producer>image</producer>
            </foreground>
         </20>
      </layer>
   </stage>
</channel>
```

**Comment by Julusian** [comment] 2019-01-05 17:47
This looks to be fixed in latest master and 2.2.0.

**Comment by gizahNL** [comment] 2019-01-29 14:35
Unfortunately the issue is still present in build today from master.

Files correctly get scheduled into background, but do not automatically start playing. Forcing a play using play CHAN-LAYER does force playout correctly

[caspar_loadbg_not_working.log](https://github.com/CasparCG/server/files/2808120/caspar_loadbg_not_working.log)

**Comment by Julusian** [comment] 2019-01-29 15:11
What does INFO produce in the latest builds?

**Comment by TondaKrist** [comment] 2019-01-30 11:05
Have to confirm, that AUTO does not work for some files. Accoriding to INFO it looks, that server thinks it has not reach end and stucks at last frame. INFO returns this:

`<time>913.218</time>
<time>913.220</time>`

**Comment by gizahNL** [comment] 2019-03-04 08:46
Is there any update on this? 

This is currently the only issue that is keeping us from running 2.2 in ACC environment

**Comment by swordh** [comment] 2019-03-07 08:38
I have the same issue, It occurs with certain files not ending, and since it's not ending, the next file won't start.  I have encountered the issue with two videos, one at 30 fps and one with 50 fps, the channel is 50 fps. When re-encoding the 30 fps file to 50 fps, the issue was "resolved", but when re-encoding the 50 fps file, the file got 1 frame shorter for some reason, the issue remained.

**Comment by TondaKrist** [comment] 2019-03-12 14:32
Is there any way how to handle this error? Have you found at least some walk around for this bug guys?

**Comment by dotarmin** [comment] 2019-03-13 05:38
> @TondaKrist Accoriding to INFO it looks, that server thinks it has not reach end and stucks at last frame. INFO returns this:

That's strange because I know @Julusian should have fixed this due to some issues in my production environment.

**Comment by TondaKrist** [comment] 2019-03-21 10:25
Still present in 2.3, video keeps hanging and AUTO is not triggered

**Comment by jdeng89** [comment] 2019-06-18 09:49
Wanted to leave my 2 cents here since I was running into this issue at GDQ. I'll likely be doing some further testing later in the week but my best guess as to what's happening here will be based on what occurred last time.

It's possible that depending on the conversion and the settings into FFMPEG, if you do a video frame rate conversion, you could end up with a video where the length of the video stream is different than the length of the audio stream. I believe this bug is hit when the audio stream ends up slightly longer than the video stream. This can happen in a number of ways, but the most direct culprit would be an interpolated conversion in FFMPEG (which is the default interpolated FPS conversion from 60 -> 59.94).

**Comment by gizahNL** [comment] 2019-06-25 15:00
> Wanted to leave my 2 cents here since I was running into this issue at GDQ. I'll likely be doing some further testing later in the week but my best guess as to what's happening here will be based on what occurred last time.
> 
> It's possible that depending on the conversion and the settings into FFMPEG, if you do a video frame rate conversion, you could end up with a video where the length of the video stream is different than the length of the audio stream. I believe this bug is hit when the audio stream ends up slightly longer than the video stream. This can happen in a number of ways, but the most direct culprit would be an interpolated conversion in FFMPEG (which is the default interpolated FPS conversion from 60 -> 59.94).

This might very well be the issue. In the testing setup I was using we have quite some files that have been re-encoded to match the channel framerate, just scanning through the files now and I can see we have quite a few files that have a (slightly) longer audio track than the video track.

**Comment by jdeng89** [comment] 2019-06-26 06:51
I also wanted to mention that we use an older version of CasparCG that not only doesn't have this problem, but just in general handles all media formats better. Planning on possibly doing a comparison and seeing exactly what changed to make the player so much more finicky.

**Comment by premultiply** [comment] 2019-06-26 15:58
There are options for the ffmpeg filter chain to truncate tracks to the shortest which may help if this is the problem here.

**Comment by jdeng89** [comment] 2019-07-08 23:17
Hello All,

After doing some further analysis and a git bisect, I believe that the commit which caused this issue is the one below. Perhaps @Julusian can provide some background as to this change and why it would cause this issue to occur?

https://github.com/CasparCG/server/commit/c28f7d4e0f5db33ccfba966bb52da8f10b227b1e#diff-4066f84dea4373a624c4e47f77456fa1

**Comment by gizahNL** [comment] 2019-07-10 15:19
> Hello All,
> 
> After doing some further analysis and a git bisect, I believe that the commit which caused this issue is the one below. Perhaps @Julusian can provide some background as to this change and why it would cause this issue to occur?
> 
> [c28f7d4#diff-4066f84dea4373a624c4e47f77456fa1](https://github.com/CasparCG/server/commit/c28f7d4e0f5db33ccfba966bb52da8f10b227b1e#diff-4066f84dea4373a624c4e47f77456fa1)

Are you sure? I would've guessed it's because Caspar now inspects the file and lets FFmpeg 'guess' the duration, which results (at least for my testfile) in the longest duration being returned. 
My test-file's video track 80ms shorter. And it get's 'stuck' at the end of the video-track; 

My patch simply increase the current frame time with the duration of the last frame each time caspar requests a new frame, which ensures that we eventually will reach the endtime and go to next file.

**Comment by jdeng89** [comment] 2019-07-10 21:50
Hmm, well I was actually testing the version of that fix on another branch which it was certainly breaking for. I noticed you opened a pull request. I can test some of our files on that and see if my initial video track / audio track thoughts were correct.

**Comment by premultiply** [comment] 2019-07-11 05:25
The shortest track should be the duration reference track. All other tracks should be cut to fit its lenght.

There are some reasons like fixed audio codec frame sizes and free running GOP-based video encoders etc. that make encoded tracks longer than intended. Some of the file container formats provide special start and end of media markers to restore the real clip boundaries.
The problem is that some decoders do not care about these markers or some encoders/muxers do not write them at all.
In this case the only chance is to select one track to be the duration reference. From the technical point of view it is the best to select the shortest track in this case as during encoding only additional data is stored.

**Comment by hreinnbeck** [comment] 2019-07-12 18:45
This behaviour could be configurable (in the config and/or with a command parameter) for those that want it.

**Comment by dimitry-ishenko** [comment] 2019-10-07 14:26
> The shortest track should be the duration reference track. All other tracks should be cut to fit its lenght.
> ...
> From the technical point of view it is the best to select the shortest track in this case as during encoding only additional data is stored.

I beg to differ. We often get files from production studios where audio tracks end before the credits at the end.

**Comment by hreinnbeck** [comment] 2019-10-08 09:17
> I beg to differ. We often get files from production studios where audio tracks end before the credits at the end.

The actual audio tracks are shorter in length - not just silence at end?

**Comment by TondaKrist** [comment] 2019-10-08 10:06
I think that NOT the shortest one, but the video track should be used for reference. We still get infinite freeze and the next clip is not triggered and keeps hanging with LOAGBG AUTO from CasparCG 2.2 and above - mostly in some mp4 files. Is there any other way how to resolve it?

**Comment by dimitry-ishenko** [comment] 2019-10-08 13:31
> > I beg to differ. We often get files from production studios where audio tracks end before the credits at the end.
> 
> The actual audio tracks are shorter in length - not just silence at end?

@hreinnbeck correct

**Closed** 2020-03-09 15:43 UTC
Labels: bug, ffmpeg-producer
