### ISSUE TITLE
PSD files for simple templates

### ISSUE THREAD

**Issue by CasparCGImport** [CasparCG/server#72] opened 2013-03-26 06:38 UTC
Converted from [SourceForge issue 3576019](http://sourceforge.net/support/tracker.php?aid=3576019), submitted by hummelstrand

To make it easier to get started, it would be a great idea to be able to read a PSD file and separate the layers so that groups could be animated in the Mixer based on names, plus text layers could be updated.

**Comment by Julusian** [comment] 2018-02-08 21:35
Duplicate of #707
@dotarmin

**Closed** 2018-02-09 07:10 UTC
Labels: duplicate, feature, testable
