### ISSUE TITLE
Video detects as audio CINF 

### ISSUE THREAD

**Issue by taurojo** [CasparCG/server#1325] opened 2020-07-01 21:56 UTC
This video is detected as AUDIO
Caspar 2.3 LTS and 2.2

It plays correctly as audio, with video. But I can’t recover the time code of the video since it detects it as an audio file.

Any solution for CINF to detect the video stream?
"25_VEGAS" AUDIO 5381194 20200701161638 481919 1/48000
It would be better to recover the info.

I see that the first Stream is Audio ID 1. I guess that’s why it detects Audio file.

Exported with Sony Vegas pro 17. Preset AVC/AAC MP4. Internet HD 1080p 25fps
In other files where the ID 1 is video there is no problem. CINF detect video file and send full frames, and timecode.

Media Info:

`General
Complete name                            : W:\25p.mp4
Format                                   : MPEG-4
Format profile                           : Base Media / Version 2
Codec ID                                 : mp42 (isom/mp42)
File size                                : 412 KiB
Duration                                 : 10 s 40 ms
Overall bit rate mode                    : Variable
Overall bit rate                         : 336 kb/s
Encoded date                             : UTC 2020-07-01 12:36:55
Tagged date                              : UTC 2020-07-01 12:36:55

Video
ID                                       : 2
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Main@L3.2
Format settings                          : CABAC / 3 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 3 frames
Format settings, GOP                     : M=4, N=15
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 10 s 40 ms
Bit rate mode                            : Variable
Bit rate                                 : 143 kb/s
Maximum bit rate                         : 16.0 Mb/s
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 25.000 FPS
Standard                                 : PAL
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.006
Stream size                              : 175 KiB (42%)
Language                                 : English
Encoded date                             : UTC 2020-07-01 12:36:55
Tagged date                              : UTC 2020-07-01 12:36:55
Color range                              : Limited
Codec configuration box                  : avcC

Audio
ID                                       : 1
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 10 s 27 ms
Bit rate mode                            : Variable
Bit rate                                 : 192 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 231 KiB (56%)
Language                                 : English
Encoded date                             : UTC 2020-07-01 12:36:55
Tagged date                              : UTC 2020-07-01 12:36:55

`

**Comment by Julusian** [comment] 2020-07-01 22:00
Duplicate of https://github.com/CasparCG/media-scanner/issues/40

**Comment by dimitry-ishenko** [comment] 2020-07-02 00:22
On a related note, do audio files support the same options as video files? Meaning, LOOP, DURATION, SEEK, LENGTH, etc

**Comment by Julusian** [comment] 2020-07-02 16:41
Also, there is a fix in a PR in the scanner repo https://github.com/CasparCG/media-scanner/pull/41

Audio files should support those fine, the unit will still be channel frames.

**Closed by Julusian** 2020-07-02 16:41 UTC
