### ISSUE TITLE
GPU memory leak with HTML template GPU acceleration enabled

### ISSUE THREAD

**Issue by TondaKrist** [CasparCG/server#1363] opened 2021-01-29 11:02 UTC
### Expected behaviour
No linear GPU memory increase after time.

### Current behaviour
When GPU acceleration is enabled in config for HTML templetes, CasparCG consumes all GPU memory available and finally fails.
```
<html>  
    <enable-gpu>true</enable-gpu>
</html>
```
_**When this option is OFF (false), it works fine over time !!!**_

### Steps to reproduce
1. enable GPU for HTML in configurtion
2. play multiple html templates until it fails

### Environment
* Server version: 2.3 LTS, 2.3.2 Beta too
* Operating system: Windows 10, Windows Server 2019
* GPU: nVidia Quadro P2000

### Screenshots
![image](https://user-images.githubusercontent.com/17853744/106266994-5853cc00-6229-11eb-9bc8-53f1d0b0acc4.png)
![image](https://user-images.githubusercontent.com/17853744/106267083-76b9c780-6229-11eb-9bf3-838e010c45e3.png)
![image](https://user-images.githubusercontent.com/17853744/106267148-8a652e00-6229-11eb-9064-4e466ea55526.png)

**Comment by rrebuffo** [comment] 2021-01-29 12:08
Duplicate of #1265

**Closed** 2023-03-06 23:26 UTC
