### ISSUE TITLE
CasparCG crashes on MP3 Icecast stream in ffmpeg producer

### ISSUE THREAD

**Issue by toontoet** [CasparCG/Server#552] opened 2017-02-10 09:38 UTC
I tried playing an icecast autio stream using the ffmpeg producer. It works often. However sometimes (1 in 5) it crashes CasparCG. There are nog sepecific errors. CasparCG just exists.

Here are some log fragments:

Here CasparCG crashed:
```
[2017-02-10 09:58:09.632] [33601] [info]    Received message from 127.0.0.1: PLAY 1-500 http://icecast2.funx.nl:8000/salto\r\n
[2017-02-10 09:58:09.634] [33679] [trace]   [ffmpeg] [http @ 0x22bd3a93eb80] request: GET /salto HTTP/1.1
[2017-02-10 09:58:09.634] [33679] [trace]   User-Agent: Lavf/56.36.100
[2017-02-10 09:58:09.634] [33679] [trace]   Accept: */*
[2017-02-10 09:58:09.634] [33679] [trace]   Range: bytes=0-
[2017-02-10 09:58:09.634] [33679] [trace]   Connection: close
[2017-02-10 09:58:09.634] [33679] [trace]   Host: icecast2.funx.nl:8000
[2017-02-10 09:58:09.634] [33679] [trace]   Icy-MetaData: 1
[2017-02-10 09:58:09.634] [33679] [trace]
[2017-02-10 09:58:09.634] [33679] [trace]
[2017-02-10 09:58:09.646] [33679] [trace]   [ffmpeg] [mp3 @ 0x22bd3e719000] Format mp3 probed with size=2048 and score=51
[2017-02-10 09:58:09.646] [33679] [info]    [ffmpeg] [mp3 @ 0x22bd3e719000] Skipping 0 bytes of junk at 0.
[2017-02-10 09:58:09.646] [33679] [trace]   [ffmpeg] [mp3 @ 0x22bd3e719000] Before avformat_find_stream_info() pos: 0 bytes read:3762 seeks:0
[2017-02-10 09:58:13.432] [35721] [info]    ############################################################################
[2017-02-10 09:58:13.433] [35721] [info]    CasparCG Server is distributed by the Swedish Broadcasting Corporation (SVT)

... restarted ...
```

Here it didn't crash:
```
[2017-02-10 09:58:00.959] [33601] [info]    Received message from 127.0.0.1: PLAY 1-500 http://icecast2.funx.nl:8000/salto\r\n
[2017-02-10 09:58:00.962] [33679] [trace]   [ffmpeg] [http @ 0x22bd1f3ee980] request: GET /salto HTTP/1.1
[2017-02-10 09:58:00.962] [33679] [trace]   User-Agent: Lavf/56.36.100
[2017-02-10 09:58:00.962] [33679] [trace]   Accept: */*
[2017-02-10 09:58:00.962] [33679] [trace]   Range: bytes=0-
[2017-02-10 09:58:00.962] [33679] [trace]   Connection: close
[2017-02-10 09:58:00.962] [33679] [trace]   Host: icecast2.funx.nl:8000
[2017-02-10 09:58:00.962] [33679] [trace]   Icy-MetaData: 1
[2017-02-10 09:58:00.962] [33679] [trace]
[2017-02-10 09:58:00.962] [33679] [trace]
[2017-02-10 09:58:00.973] [33679] [trace]   [ffmpeg] [mp3 @ 0x22bd3f82e000] Format mp3 probed with size=2048 and score=51
[2017-02-10 09:58:00.973] [33679] [info]    [ffmpeg] [mp3 @ 0x22bd3f82e000] Skipping 0 bytes of junk at 0.
[2017-02-10 09:58:00.973] [33679] [trace]   [ffmpeg] [mp3 @ 0x22bd3f82e000] Before avformat_find_stream_info() pos: 0 bytes read:2508 seeks:0
[2017-02-10 09:58:01.005] [33679] [trace]   [ffmpeg] [mp3 @ 0x22bd3f82e000] All info found
[2017-02-10 09:58:01.005] [33679] [trace]   [ffmpeg] [mp3 @ 0x22bd3f82e000] After avformat_find_stream_info() pos: 31744 bytes read:32000 seeks:0 frames:50
[2017-02-10 09:58:01.016] [33679] [info]    ffmpeg[http://icecast2.funx.nl:8000/salto||0/0] [audio-decoder] MP3 (MPEG audio layer 3)
[2017-02-10 09:58:01.016] [33679] [trace]   [ffmpeg] [Parsed_abuffer_0 @ 0x22bd1f42ab40] Setting 'time_base' to value '1/48000'
[2017-02-10 09:58:01.016] [33679] [trace]   [ffmpeg] [Parsed_abuffer_0 @ 0x22bd1f42ab40] Setting 'sample_rate' to value '48000'
[2017-02-10 09:58:01.016] [33679] [trace]   [ffmpeg] [Parsed_abuffer_0 @ 0x22bd1f42ab40] Setting 'sample_fmt' to value 's32'
[2017-02-10 09:58:01.016] [33679] [trace]   [ffmpeg] [Parsed_abuffer_0 @ 0x22bd1f42ab40] Setting 'channel_layout' to value '0x3'
[2017-02-10 09:58:01.016] [33679] [debug]   [ffmpeg] [Parsed_abuffer_0 @ 0x22bd1f42ab40] tb:1/48000 samplefmt:s32 samplerate:48000 chlayout:0x3
[2017-02-10 09:58:01.016] [33679] [trace]   [ffmpeg] [AVFilterGraph @ 0x22bd3a93e180] query_formats: 3 queried, 6 merged, 0 already done, 0 delayed
[2017-02-10 09:58:01.016] [33679] [debug]
[2017-02-10 09:58:01.016] [33679] [debug]   +------------------+
[2017-02-10 09:58:01.016] [33679] [debug]   | Parsed_abuffer_0 |default--[48000Hz s32:stereo]--Parsed_anull_1:default
[2017-02-10 09:58:01.016] [33679] [debug]   |    (abuffer)     |
[2017-02-10 09:58:01.016] [33679] [debug]   +------------------+
[2017-02-10 09:58:01.016] [33679] [debug]
[2017-02-10 09:58:01.016] [33679] [debug]                                                          +----------------+
[2017-02-10 09:58:01.016] [33679] [debug]   Parsed_abuffer_0:default--[48000Hz s32:stereo]--default| Parsed_anull_1 |default--[48000Hz s32:stereo]--Parsed_ab
uffersink_2:default
[2017-02-10 09:58:01.016] [33679] [debug]                                                          |    (anull)     |
[2017-02-10 09:58:01.016] [33679] [debug]                                                          +----------------+
[2017-02-10 09:58:01.016] [33679] [debug]
[2017-02-10 09:58:01.016] [33679] [debug]                                                        +----------------------+
[2017-02-10 09:58:01.016] [33679] [debug]   Parsed_anull_1:default--[48000Hz s32:stereo]--default| Parsed_abuffersink_2 |
[2017-02-10 09:58:01.016] [33679] [debug]                                                        |    (abuffersink)     |
[2017-02-10 09:58:01.016] [33679] [debug]                                                        +----------------------+
[2017-02-10 09:58:01.016] [33679] [debug]
[2017-02-10 09:58:01.016] [33679] [debug]
[2017-02-10 09:58:01.016] [33679] [info]    transition[empty=>ffmpeg[http://icecast2.funx.nl:8000/salto||0/0]] Initialized
[2017-02-10 09:58:01.016] [33679] [debug]   Executed command (0.057s): PLAY
[2017-02-10 09:58:01.016] [33679] [info]    Sent message to 127.0.0.1:202 PLAY OK\r\n
```

**Comment by toontoet** [comment] 2017-02-13 16:38
On a windows version of 2.1.0 we got a similar failure. But instead of just crashing some information was logged in the CasparCG logfile:

[ccg_error_log_-_freezing_audio_stream_-_win7_-_trace.txt](https://github.com/CasparCG/Server/files/771703/ccg_error_log_-_freezing_audio_stream_-_win7_-_trace.txt)

**Comment by saltomodules** [comment] 2017-02-13 19:53
We've also tested quite a few icecast streams from different sources.  MP3 streams do crash casparcg. However, the ogg streams we've tested so far do not crash casparcg.

Check for instance:
PLAY 1-1 http://51.15.48.0:8000/caribbeanfm.ogg
PLAY 1-1 http://51.15.48.0:8000/caribbeanfm

The latter one is mp3. In our testing setup it crashes casparcg on linux (and gives errors on windows) within a few tries. The first ogg one doesn't.

Issue has been replicated with the latest build from 13-02-2017: 
2.1.0.3318 cfc2713 Beta 1

**Comment by toontoet** [comment] 2017-02-13 20:19
An AAC stream also works as expected. Wasn't able to crash CasparCG using http://icecast.funx.nl:8000/funx.aac

**Comment by saltomodules** [comment] 2017-05-01 19:11
It might be useful to add that the casparcg console gives slightly more information than the log files when capsar crashes on an audio stream. In the console it says  the crash is caused by a sementation fault:

```
[2017-05-01 18:38:18.638] [170155] [info]    DeckLink Duo 2 [4-4|1080i5000] Reference signal: not detected.
[2017-05-01 18:38:21.759] [170082] [info]    async_event_server[:5250] Accepted connection from 127.0.0.1 (1 connections).
[2017-05-01 18:38:26.789] [170082] [info]    Received message from 127.0.0.1: PLAY 1-1 http://51.15.48.0:8000/caribbeanfm\r\n
[2017-05-01 18:38:31.184] [170159] [info]    [ffmpeg] [mp3 @ 0x1356920ec600] Skipping 299 bytes of junk at 0.
[2017-05-01 18:38:31.195] [170159] [warning] [ffmpeg] [mp3 @ 0x1356923bd480] Channel layout 'mono' with 1 channels does not match specified number of channels 2: ignoring specified channel layout
[2017-05-01 18:38:31.205] [170159] [info]    ffmpeg[http://51.15.48.0:8000/caribbeanfm||0/0] [audio-decoder] MP3 (MPEG audio layer 3)
[2017-05-01 18:38:31.206] [170159] [info]    transition[empty=>ffmpeg[http://51.15.48.0:8000/caribbeanfm||0/0]] Initialized
[2017-05-01 18:38:31.206] [170159] [info]    Sent message to 127.0.0.1:202 PLAY OK\r\n
Segmentation fault (core dumped)
Type "q" to close application.
Logging [info] or higher severity to log/

[2017-05-01 18:38:34.570] [170252] [info]    ############################################################################
[2017-05-01 18:38:34.570] [170252] [info]    CasparCG Server is distributed by the Swedish Broadcasting Corporation (SVT)
```

**Comment by ronag** [comment] 2017-12-18 15:59
Closing in favor of #636. Please create a new issue if it still remains after that one is resolved.

**Closed by ronag** 2017-12-18 15:59 UTC
Labels: bug, ffmpeg, found in 2.1.0
