### ISSUE TITLE
Incorrect field order when playing interlaced clips

### ISSUE THREAD

**Issue by dotarmin** [CasparCG/server#1336] opened 2020-08-28 10:09 UTC
### Expected behaviour
Interlaced material should play fields in correct order.

### Current behaviour
Incorrect fields order when playing interlaced material

### Notes
The attached file has been rendered with latest After Effects. 
Can be reproduced easily by rendering a new file.

----

### Steps to reproduce
1. Upload the attached file to CasparCG Server v2.3.0 LTS Stable
2. Play clip
3. Repeat step 2 and you will experience the incorrect field order

### Environment
* Commit: a4a7c05
* Server version: v2.3.0 LTS Stable
* Operating system: Windows 7

----

### Attachments
[LAS-Kortbumper1-NoLogo-Caspar.mov.zip](https://github.com/CasparCG/server/files/5141458/LAS-Kortbumper1-NoLogo-Caspar.mov.zip)

**Comment by dotarmin** [comment] 2020-09-10 10:44
@Julusian @ronag do you have any idea what can be causing this?

**Comment by dotarmin** [comment] 2020-09-11 06:18
Solved by setting the ffmpeg.producer.auto-interlace flag to all in casparcg.config.

**Comment by dotarmin** [comment] 2020-09-30 06:21
We need to find the root cause of this. Even if it works by setting the auto-interlace flag (see previous comment) I'm still curious why this is the case when the file indicates it's interlaced according to it's metadata.

**Comment by sendust** [comment] 2021-03-04 05:23
Here is another hint.
Tested with casparcg server version [2.3.2 f01b1efa2 Dev]
1080i5994, HDSDI output
Decklink driver 11.5.1
Windows 10


1. Create interlaced mxf clip with ffmpeg
  (NTSC country)
   ffmpeg -f lavfi -i testsrc2=r=59.94:size=480x270 -filter_complex scale=1920x1080[v1];[v1]tinterlace=4[v2];[v2]setfield=tff -top 1 -c:v mpeg2video -g 15 -b:v 30000k -bufsize 30000k -maxrate 30000k -flags +ilme+ildct -an interlace.mxf 

 (PAL country)
   ffmpeg -f lavfi -i testsrc2=r=50:size=480x270 -filter_complex scale=1920x1080[v1];[v1]tinterlace=4[v2];[v2]setfield=tff -top 1 -c:v mpeg2video -g 12 -b:v 30000k -bufsize 30000k -maxrate 30000k -flags +ilme+ildct -an interlace.mxf


2. Repeat load and play interlace.mxf in casparcg server

3. Record playback signal with blackmagic design media express or other recording program.

4. playback recorded file with vlc without deinterlacing

5. Suppose field number is start from 0
  Expected behaviour :
  - frame 0 (field 0 + field 1)
  - frame 1 (field 2 + field 3)
  - frame 2 (fidle 4 + field 5)
 
  Wrong result : (You can see abnormal frame)
  - frame 0 (field 1 + field 2)
  - frame 1 (field 3 + field 4)
  - frame 3 (field 5 + field 6)
 
6. Sometimes the wrong result comes out when you repeat the load and play, and sometimes the good result comes out.
  Attachments show good and bad results

![frame_GOOD](https://user-images.githubusercontent.com/67322016/109915399-1f5dba00-7cf5-11eb-80fd-24192bac367d.png)
![frame_NG](https://user-images.githubusercontent.com/67322016/109915401-208ee700-7cf5-11eb-8003-394500aa6da3.png)

**Comment by amwtech** [comment] 2022-05-16 10:55
I ran some PAL and 1080i5000 tests using server version 2.3.3_LTS (downloaded from the Github distribution). My results match those reported by sendust. The test content was played out of a CasparCG channel via a BlackmagicDesign UltraStudio 4k as HD-SDI, recording the signal into a Blackmagic Hyperdeck Studio Mini which used ProRes422 codec. The recorded videos are imported to FCPX, and single frames or sequences of frames are exported as PNG stills.

I created test signals with interlaced, progressive 25Hz and progressive 50Hz sources. With the CasparCG channel set to PAL or 1080i5000 playing the test footage showed about a 50% probability of the SDI output having bad interlace in which an output frame is composed of field 2 from source frame 1, and the field 1 from source frame 2. 

My test videos are available at [https://github.com/amwtech/CasparCG_Test_Signals](url). They are designed to make it easy to identify the temporal source, and to see if spatial offset has been used on a field.

An example with correct interlacing is shown below.
![ch1080i5000-src1080i25-good](https://user-images.githubusercontent.com/86308191/168569215-86171c43-c1c3-4de9-81ef-f02520077ca7.png)

The same test signal played out with wrong interlacing is shown below.
![ch1080i5000-src1080i25-bad](https://user-images.githubusercontent.com/86308191/168569498-4334e91d-0f76-422c-8752-fbb7dd2b4d73.png)

Careful examination of the patterns of lines in the blocks shows the fields are spatially offset from their source positions to give correct temporal sequence. The offset is visible because the top and bottom lines in the block have gone grey.

Progressive 25Hz source test signal also has around a 50% potential to produce poor output. The example below shows a frame with good interlacing.
![ch1080i5000-src1080p25-good](https://user-images.githubusercontent.com/86308191/168570474-b8a4f09a-63f7-4f71-97c6-6c2caa8376e0.png)

And the picture below shows the same source file output with bad interlacing.
![ch1080i5000-src1080p25-bad](https://user-images.githubusercontent.com/86308191/168570599-50bffb67-85b5-4a37-8d02-2d46c6af3f88.png)

The progressive test pattern comprises two sets of 1-scan line high white lines that overlap horizontally. The left side of the block is labelled X, and has the lines at what are field 1 in interlaced operation. The block labelled Y is set for display on field 2 in an interlace output. The progressive source bad interlaced output matches the temporal content makeup seen in the interlace source bad interlace output.

I also tested a source video with 50Hz progressive content. All tests showed the same result with a correctly interlaced 1080 line output being created by 540 lines from frame 0 and 540 lines from frame 1. The source frame pairings always started with an even numberered source frame (first output frame made from source frame 0 and source frame 1, next output frame made from source frame 2 and source frame 3 etc). This conversion shows good processing and is optimal for real time replay in the i25 channel.

I also did some tests of the SDI output from a channel using Javascript and the RequestAnimationFrame() callback to move a pattern of white lines. I observed that in a channel mode set at 1080i5000 the requests occured every 20ms (i.e. field rate). Requests happened every 40ms for a channel mode set at 1080p2500, and 20ms for a channel mode set at 1080p5000.

I tried making a graphic that used frame based animation using alternate calls to requestAnimationFrame() to advance the animation. This process also showed a 50% probability of not aligning to the SDI output frame, producing the output illustrated below. This non-alignment is expected because there is no Javascript requestAnimation callback that identifies when an output **frame** is starting, the callback just identifies a field is starting.

![Ch1080i5000_RqAF_bad](https://user-images.githubusercontent.com/86308191/168573770-2ede66aa-9e4a-49db-b43b-392fa8471dd0.png)

I mused on what could be happening. So the following is speculation (I'm not yet sufficiently familiar with the timing processes in the server C++ code and buffer passing from producers and to consumers).

My understanding from other postings here and in the CasparCG forum is that Server version 2.3 uses a progressive process through the channel mixer, thus converting an interlace source frame into two progressive frames at double teh _source frame_ rate. If the mixer is set to "pass all" (no processing required) the SDI producer strips out the unwanted extra lines inserted by the producer making two progressive frames back into a single output frame.

How does the process pipeline know the source field id from the progressive frame formed by that field? If this data is not available, how can the consumer know which progressive frame is originally a field type 1 enabling correct reconstruction of a source frame? A slip of one progressive frame in the process chain would create the stable merge of content from two source frames we see in practical testing.

I would also suggest that there is a requirement in the CEF code to add a special reqestAnimationFrame() callback that is called only when there is an output interlace frame starting, thus synchronising the CEF animation to the SDI field ordered output.

Andy Woodhouse.

**Comment by Julusian** [comment] 2022-05-17 14:15
I am looking into this for a client, as part of investigating moving to 2.3 from 2.1.
We have observed the same field order mismatch when playing interlaced clips, and have also found that when looping clips it will often switch between the two states.
While it can be 'resolved' by forcing deinterlacing for the clips, this does mean that sometimes the output will be purely taken from the interpolated rather than source data, and so will be rather lossy.


> My understanding from other postings here and in the CasparCG forum is that Server version 2.3 uses a progressive process through the channel mixer, thus converting an interlace source frame into two progressive frames at double the source frame rate. If the mixer is set to "pass all" (no processing required) the SDI producer strips out the unwanted extra lines inserted by the producer making two progressive frames back into a single output frame. 

Yes, when doing 50i, the mixer is running 50p and the decklink consumer interleaves two of the mixed frames into one for output.

> How does the process pipeline know the source field id from the progressive frame formed by that field? If this data is not available, how can the consumer know which progressive frame is originally a field type 1 enabling correct reconstruction of a source frame? A slip of one progressive frame in the process chain would create the stable merge of content from two source frames we see in practical testing.

Quite simply it doesnt know. And from a bit of looking at how the ffmpeg producer is setup, it cant know. It is setup to within the filter to convert the framerate to the 50p that the channel is running at, and optionally deinterlace the clip. I dont see how it could give us the needed metadata to know which field a frame belongs to.
The best option I can see is to count the frames it gives us and pair them up as field1 and field2.

I have a couple of ideas on how to propagate this throughout the channel that I shall experiment with. Both do require changing method signatures on producers and consumers, so are going to be quite a sprawling change

> I would also suggest that there is a requirement in the CEF code to add a special reqestAnimationFrame() callback that is called only when there is an output interlace frame starting, thus synchronising the CEF animation to the SDI field ordered output.

Im not sure that we can do that. CEF is very bad at giving frames on a timer. If nothing changed, it doesnt provide us with a frame, and combine that with the the async nature of we call `reqestAnimationFrame()` and some time later we get a frame, we wouldnt be able to reliably figure out if what we were given by CEF was field1 or field2

**Comment by Julusian** [comment] 2022-09-13 15:38
I have a PR open for this #1440
I would appreciate some further testing from those who have experienced this issue before I merge it

**Comment by amwtech** [comment] 2022-09-16 15:08
I have tried to test this build, havng added scanner to the same folder as the test build. Currently I get no output to any consumer, and all commands issued at the console report a fail. Changing the log level reports the new level, for example to "trace", but this does not change the actual log behaviour.

I know the hardware SDI output chain works with the master branch of server 2.3.3_LTS, and I have tried the test build using the same casparcg.config, also getting no output.

I will try more tests later.

**Comment by Julusian** [comment] 2023-02-16 12:32
I have merged the PR that I believe will resolve this, and in my testing has ensured playback uses the correct field alignment.
I'm going to close this issue unless someone still has issues.

So far this field alignment is only supported by decklink producer&consumer, and ffmpeg produer. any other producers and consumers are not looking at the field alignment information, so will likely behave as before. I am expecting them to be fixed up as needed by someone who knows how to test them in further PRs

**Closed by Julusian** 2023-02-16 12:32 UTC
Labels: type/bug
