### ISSUE TITLE
OSC countdowns not working?

### ISSUE THREAD

**Issue by ronag** [CasparCG/server#738] opened 2018-02-05 18:17 UTC
@dotarmin I need a client guy to help me here.

**Comment by dotarmin** [comment] 2018-02-06 10:10
What countdowns, for clips?

**Comment by ronag** [comment] 2018-02-06 11:32
@dotarmin yes, we could take a look together on friday?

**Comment by dotarmin** [comment] 2018-02-06 11:34
@ronag Sure, I think this is a duplicate of #739 of vice versa.

**Comment by dotarmin** [comment] 2018-02-08 08:48
@ronag We talked about this yesterday over Skype, is this fixed in the media-scanner by using fps when possible instead of timebase? I will create an issue for the Client regarding this.

**Comment by ronag** [comment] 2018-02-08 10:54
No, that was regarding CLS & CINF. Though it might have fixed the countdowns. Do they work now?

**Comment by dotarmin** [comment] 2018-02-08 20:01
> @ronag No, that was regarding CLS & CINF. Though it might have fixed the countdowns. Do they work now?

I will verify this tomorrow because I wasn't able to do it today.

**Comment by ronag** [comment] 2018-02-08 20:43
@dotarmin @5opr4ni was helping me today. We'll take a look tomorrow together.

**Comment by malmgrenola** [comment] 2018-02-09 10:23
Hey @ronag I've set up a (non working) OSC on gfx20 in lab for you to test on a independent machine.

**Closed** 2018-02-09 12:48 UTC
Labels: bug
