### ISSUE TITLE
608/708 closed captions

### ISSUE THREAD

**Issue by tvadi** [CasparCG/server#1400] opened 2021-11-06 07:52 UTC
Needed-  608/708 embedded captions out Decklink SDI and if possible, full screen HDMI.

Using 1080i or 720p mpeg-2 files with embedded 608/708 captions but CasparCG does not pass the captions.

Testing with Decklink 4k extreme..

Looking for any help in this, willing to pay a developer or if someone can point me in the right direction, I will dig in.  Thanks!

**Comment by gizahNL** [comment] 2021-11-14 06:58
I've had this (somewhat) working in the past. Not out via SDI though, but via NDI.

Take a look at: https://github.com/in2ip/server

**Comment by gizahNL** [comment] 2021-11-18 08:42
@tvadi: feel free to contact me at gijs [AT] peskens [DOT] net if you need more help to integrate 608/708 support

**Comment by tvadi** [comment] 2021-12-11 01:05
@gizahNL I emailed you, no word yet but looking forward to getting in contact.  I see some Git mentioning 708, do these work? [https://github.com/in2ip/server/tree/subtitling-cea708-passthrough](url)  [https://github.com/in2ip/server/tree/cea708](url)

**Comment by hreinnbeck** [comment] 2021-12-19 19:34
These might be useful references for 708 with Decklink:

OBS Studio 708 implementation:
https://github.com/obsproject/obs-studio/commit/923f06bfa6ea80a432f182b50bb6dc5256ba2560

FFMPEG 708 decklink implementation:
https://github.com/vanlin/ffmpeg/commit/8732dfa99549b8e233b50956cb27031e18806685

libklvanc:
https://github.com/stoth68000/libklvanc

**Comment by tvadi** [comment] 2022-01-05 15:59
Got ffmpeg to pass captions on SDI with the help of libklvanc, thanks!!  With CasparCG could implement libklvanc...

**Comment by Julusian** [comment] 2023-03-06 23:03
duplicate of #92

**Closed by Julusian** 2023-03-06 23:03 UTC
Labels: type/enhancement, feedback/pull request wanted

**Comment by dedicatedbroadcastsolutions** [comment] 2025-05-01 07:04
I have found a developer to work on this, please contact me on the CasparCG forum or contact Radiant Light Broadcasting (rlb.org) if you would like to help fund captions for CasparCG.  We are working on file to file first, then will add decklink to decklink.  Any help would be appreciated.
