### ISSUE TITLE
Not updating text HTML template 2.3

### ISSUE THREAD

**Issue by alfredo3141** [CasparCG/server#1431] opened 2022-05-30 12:36 UTC
In the config file when you have set  html to enable-gpu to true the graphics are not always updated after you have sent the update command for Consumer and Decklink.  

It appears to happens a bit randomly when you do the graphics, on one computer we had the problem directly on start but on some it took like 20 minutes. You had to playout multiple graphics signs during the period and after 10-20 minutes it's starts to failure.  

What I have seen it's only the text that's not updates, if you have an animation it will be played and if you have added the text before animation the text will be updated. When it bigger changes,  it work but not smaller. 

It's tested on both Radeon and Nivida cards and Intel integrated graphic the same issue. On Windows 11 it's appears more frequently. I have tested on 2.3.1 and 2.3 the same issue.

**Comment by Sidonai-1** [comment] 2022-05-30 13:30
Hi Alfredo,

I've experienced something similar sometimes.

Were you opening the casparcg.exe directly or were you using some kind of launcher?

**Comment by alfredo3141** [comment] 2022-05-30 13:39
Hi Carlos 

Directly no launcher have tested with .bat file to same problem.

**Comment by alfredo3141** [comment] 2022-09-06 12:54
https://user-images.githubusercontent.com/13998929/188637315-c7d06880-7e17-4695-b0cd-b019fe921a57.mp4

You see when the clock stops it should update the resultlist to the right but it don't . Like the last second it appears, during the alpha animation. 

When the graphics stops I only send stop command. The consumer works properly.

**Comment by pbelbin** [comment] 2022-11-03 13:03
It's *possible* that #1441 is another manifestation of the same issue being described here.  Both are doing infrequent updates, and sometimes, the update is not visible in the output. It's unclear whether CEF isn't being told to show the updated content, or whether CEF isn't generating the output, or whether CasparCG isn't providing the latest output. But it does appear that *something* isn't happening like it should.

**Comment by pbelbin** [comment] 2022-11-03 13:15
@alfredo3141 would you mind giving the template provided in #1441 a try on your windows 11 system and see if it happens to skip clock time updates there too? Seems like you're saying on windows 11 the issue is happening more often than with windows 10.  The symptom shows up as the clock showing the same time for *more than 1 second* and jumping to showing the correct time.

**Comment by Julusian** [comment] 2023-03-06 22:49
I am pretty confident this is a duplicate of #1454 or #1441, so I shall close this in favor of those

**Closed by Julusian** 2023-03-06 22:49 UTC
