### ISSUE TITLE
Clip freezes in v2.2 after 32979 fields and SEEK delays freezing

### ISSUE THREAD

**Issue by saltomodules** [CasparCG/server#1010] opened 2018-05-31 14:53 UTC
### Expected Behaviour

Clip thats 60 minutes long plays completely from start to end.

### Current Behaviour

Clip in question plays without issue in CasparCG 2.1 but stops after 32979 fields in 2.2. 

However if you add a SEEK to the PLAY command the clip doesn't stop at the same timecode. It starts at the seek point and continues to run until approximately the same amount of fields has passed. When the clip freezes an `EOF frames_out` trace message is visible in the log file:

**Example without seek**
```
[2018-05-31 15:31:17.984] [info]    Received message from Console: play 1-1 music\r\n
[2018-05-31 15:31:17.984] [debug]   Executing command: PLAY
[2018-05-31 15:31:17.985] [trace]   [ffmpeg] [NULL @ 00000000118C04C0] Opening '../media/music.mp4' for reading  
[...]
[2018-05-31 15:42:20.131] [trace]   [ffmpeg] [h264 @ 0000000017F31640] nal_unit_type: 1, nal_ref_idc: 2
[2018-05-31 15:42:20.131] [trace]
[2018-05-31 15:42:20.171] [trace]   [ffmpeg] [h264 @ 0000000017F31640] nal_unit_type: 5, nal_ref_idc: 3
[2018-05-31 15:42:20.171] [trace]
[2018-05-31 15:42:20.171] [trace]   [ffmpeg] [h264 @ 0000000017F31640] nal_unit_type: 1, nal_ref_idc: 2
[2018-05-31 15:42:20.171] [trace]
[2018-05-31 15:42:20.321] [trace]   [ffmpeg] [Parsed_fps_2 @ 0000000017EA2400] EOF frames_out:32979 delta:1
[2018-05-31 15:42:20.321] [trace]
[2018-05-31 15:42:20.321] [trace]   [ffmpeg] [Parsed_fps_2 @ 0000000017EA2400] Duplicating frame.
[2018-05-31 15:42:20.321] [trace]
```

**Example with seek**
```
[2018-05-30 11:53:36.537] [info]    Received message from Console: play 1-1 music seek 10000\r\n
[2018-05-30 11:53:36.537] [debug]   Executing command: PLAY
[2018-05-30 11:53:36.538] [trace]   [ffmpeg] [NULL @ 00000000122CA700] Opening '../media/music.mp4' for reading
[...]
[2018-05-30 12:04:24.542] [trace]
[2018-05-30 12:04:24.542] [trace]   [ffmpeg] [h264 @ 0000000020ED08C0] nal_unit_type: 1, nal_ref_idc: 0
[2018-05-30 12:04:24.542] [trace]
[2018-05-30 12:04:24.582] [trace]   [ffmpeg] [h264 @ 0000000020ED08C0] nal_unit_type: 1, nal_ref_idc: 0
[2018-05-30 12:04:24.582] [trace]
[2018-05-30 12:04:24.582] [trace]   [ffmpeg] [h264 @ 0000000020ED08C0] nal_unit_type: 1, nal_ref_idc: 0
[2018-05-30 12:04:24.582] [trace]
[2018-05-30 12:04:24.731] [trace]   [ffmpeg] [Parsed_fps_2 @ 000000001260FC40] EOF frames_out:32259 delta:1
[2018-05-30 12:04:24.731] [trace]
[2018-05-30 12:04:24.731] [trace]   [ffmpeg] [Parsed_fps_2 @ 000000001260FC40] Duplicating frame.
[2018-05-30 12:04:24.731] [trace]
```

A few seconds before the freeze a long list of `adding silence` messages is visible in the logs and you can hear an audio hick up. for instance:
```
[2018-05-31 15:42:14.859] [trace]   [ffmpeg] [h264 @ 0000000017F31640] nal_unit_type: 1, nal_ref_idc: 0
[2018-05-31 15:42:14.859] [trace]   
[2018-05-31 15:42:14.881] [debug]   [ffmpeg] [Parsed_aresample_1 @ 00000000180EB200] [SWR @ 0000000017D000C0] adding 16384 audio samples of silence
[2018-05-31 15:42:14.881] [debug]   
[2018-05-31 15:42:14.881] [debug]   [ffmpeg] [Parsed_aresample_1 @ 00000000180EB200] [SWR @ 0000000017D000C0] adding 16384 audio samples of silence
[2018-05-31 15:42:14.881] [debug]   
[2018-05-31 15:42:14.881] [debug]   [ffmpeg] [Parsed_aresample_1 @ 00000000180EB200] [SWR @ 0000000017D000C0] adding 16384 audio samples of silence
[2018-05-31 15:42:14.881] [debug]   
[2018-05-31 15:42:14.882] [debug]   [ffmpeg] [Parsed_aresample_1 @ 00000000180EB200] [SWR @ 0000000017D000C0] adding 16384 audio samples of silence
[2018-05-31 15:42:14.882] [debug]   
[...]
[2018-05-31 15:42:15.178] [debug]   [ffmpeg] [Parsed_aresample_1 @ 00000000180EB200] [SWR @ 0000000017D000C0] adding 16384 audio samples of silence
[2018-05-31 15:42:15.178] [debug]   
[2018-05-31 15:42:15.178] [debug]   [ffmpeg] [Parsed_aresample_1 @ 00000000180EB200] [SWR @ 0000000017D000C0] adding 14288 audio samples of silence
[2018-05-31 15:42:15.178] [debug]   
[2018-05-31 15:42:15.178] [trace]   [ffmpeg] [h264 @ 0000000017F31640] nal_unit_type: 1, nal_ref_idc: 0   
```

We use video-mode 1080i5000 but issue is also present with the default configuration (and also in progressive modes).

### Steps to Reproduce

- Play attached clip with default config. 
- Clip should freeze slightly before the 11 minute mark. 
- If you use a SEEK the freezing gets delayed with approximately that amount.

### Environment

 Issue is observed on both an ubuntu and a windows 7 system:
   
   **System 1**

    CasparCG Server version:
    2.2.0.3407 dc49d50c5 Beta 1
    video-mode 1080i5000    

    Operating system:
    Ubuntu 18.04

    Graphics driver:
    Nvidia 390.42  (for GTX1050)

    Decklink drivers:
    Blackmagic Design BlackmagicIO driver 10.10a3

  **System 2**

    CasparCG Server version:
    2.2.0.4 abdbcc19 Beta 1
    video-mode 1080i5000    
    
    Operating system:
    Win 7 x64
    
    Graphics driver:
    Nvidia 391.01 (for GTX660)
    
    Decklink drivers:
    none    

### Attachments
https://www.dropbox.com/s/orm9f7ef6u09vpn/music.mp4?dl=0
duration: 59m48s
size: 1.9 GB

**Comment by dotarmin** [comment] 2018-06-02 05:31
Could be similar to issue described in #953. Now, I'm not sure at all if those issues are the same or even relate to each other but could be worth to mention it because both of them makes clips to freeze.

**Comment by ronag** [comment] 2018-07-18 07:49
The problem is with the file. It has discontinuous timestamp. Will try an easy workaround.

**Comment by ronag** [comment] 2018-07-18 14:57
Seems to be a ffmpeg bug :/. Fixed in master. Please test.

**Closed by ronag** 2018-07-18 14:57 UTC

**Comment by saltomodules** [comment] 2018-07-27 19:45
Tested. Issue is solved. Thanks!
