### ISSUE TITLE
support 10bit for HDR

### ISSUE THREAD

**Issue by shenyanjie0807** [CasparCG/server#1266] opened 2020-03-28 03:39 UTC
More TV stations join UHD&HDR broadcasting,Caspar needs to go further, supporting 10bit or higher color will be more widely used. 10bit is just the starting point for HDR.

**Comment by premultiply** [comment] 2020-03-28 06:05
https://github.com/CasparCG/server/pull/1253#issuecomment-596365957

**Comment by Julusian** [comment] 2020-03-30 10:33
Duplicate of https://github.com/CasparCG/server/issues/325

**Closed by Julusian** 2020-03-30 10:33 UTC
