### ISSUE TITLE
CasparCG Subtitle Consumer and producer

### ISSUE THREAD

**Issue by dust63** [CasparCG/server#369] opened 2015-08-11 21:45 UTC
Hi,

My idea is to implement a new producer and consumer to insert STL or SRT... in VBI, VANC of SDI.
Another function is to burn subtitles on the screen.

What do you think of this ?

Regards.

**Comment by deedos** [comment] 2015-08-11 21:58
Amazing!
totally support! the idea.
cheers

2015-08-11 18:45 GMT-03:00 dust63 <notifications@github.com>:

> Hi,
>
> My idea is to implement a new producer and consumer to insert STL or
> SRT... in VBI, VANC of SDI.
> Another function is to burn subtitles on the screen.
>
> What do you think of this ?
>
> Regards.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CasparCG/Server/issues/369>.
>



-- 
Daniel Roviriego
(21) 35920701
(21) 99561654

**Comment by TomKaltz** [comment] 2015-08-11 23:24
@dust63 are you actively working on implementing this?

**Comment by dust63** [comment] 2015-08-12 13:28
No, i'm not c++ développer so i can't produce this. I make the feature
request if someone have some time to develop this. I can provide some
documentation and specs if some one need.
Le 12 août 2015 00:24, "Thomas Kaltz III" <notifications@github.com> a
écrit :

**Comment by cooliobr** [comment] 2022-02-25 19:20
Eu implementei para DVBSUB, ficou perfeito

**Comment by STL1811** [comment] 2022-11-04 12:14
Hi @cooliobr, 
You did it for DVBSUB or you would like that the feature exist ?

**Comment by cooliobr** [comment] 2022-11-04 12:16
i did it but i dont use casparcg anymore.

**Comment by STL1811** [comment] 2022-11-04 12:19
Did you share  your implementation ?

**Comment by cooliobr** [comment] 2022-11-04 12:23
Sorry, i can't share this. i sell it to a company.

**Comment by cooliobr** [comment] 2022-11-04 12:24
today i using ffplayout, it is better, in one i7 i can run 15 channels

**Comment by STL1811** [comment] 2022-11-04 13:49
Ok, I see it in your repository. Thank you

**Comment by Julusian** [comment] 2023-03-06 23:04
duplicate of #92

**Closed by Julusian** 2023-03-06 23:04 UTC
Labels: type/feature, feedback/pull request wanted
