### ISSUE TITLE
THUMBNAIL RETRIEVE is slow with latest media-scanner

### ISSUE THREAD

**Issue by ianshade** [CasparCG/server#1488] opened 2023-05-29 09:39 UTC
### Expected behaviour
`THUMBNAIL RETRIEVE` is fast (within tens of milliseconds), as it used to be with older media scanner releases.

### Current behaviour
`THUMBNAIL RETRIEVE` with media-scanner [v1.1.0](https://github.com/CasparCG/media-scanner/commit/816854b8a91f39e265b73214f6b6c72f947f44c7) takes seconds. Usually upwards of 2 seconds, but reaching 5 seconds for larger thumbnails.

----

### Steps to reproduce
1. Enable debug logging in casparcg.config to see command timing
2. Start media-scanner [v1.1.0](https://github.com/CasparCG/media-scanner/commit/816854b8a91f39e265b73214f6b6c72f947f44c7)
3. Start CasparCG
4. Execute a `THUMBNAIL RETRIEVE [filename]` command

### Environment
* Commit: b0ecbee
* Server version: 2.4
* Operating system: Windows 11

---

### Screenshots
With media-scanner from https://github.com/nrkno/sofie-casparcg-media-scanner/releases/tag/v1.6.1
![image](https://github.com/CasparCG/server/assets/9103996/fb24ec46-4797-4c22-8822-ed3185ec1f3f)

With media-scanner v1.1.0
![image](https://github.com/CasparCG/server/assets/9103996/34edc625-2314-475a-a8dd-ff82edb59cc0)

Media-scanner v1.1.0 returns the same thumbnail over HTTP consistently quickly, which makes me think this is an issue in CasparCG's  HTTP client implementation, not a media-scanner issue.
![image](https://github.com/CasparCG/server/assets/9103996/2e5cb40c-6612-49fb-92e8-0b0dbe41eaee)

**Comment by Julusian** [comment] 2023-05-29 12:16
I've given this a quick try on linux, in the console window, and it doesn't look to be in the scale of seconds (testing with AMB). Some testing on windows should be done too

**Comment by andr9528** [comment] 2023-06-15 13:23
I can add that at TV2 we use Windows 10, and i were the one to first notice this and message Krzysztof about it.
All my other settings appear to be just as mentioned by OP.

**Comment by Julusian** [comment] 2023-09-04 15:01
This appears to have been caused by https://github.com/CasparCG/media-scanner/pull/48

Looking at wireshark, it is first attempting to connect to `::1`, then after 2s it retries on `127.0.0.1`. This will be because by default caspar is configured to connect to `localhost`. Changing that out in the caspar.config to `127.0.0.1` avoids this.

I am unable to reproduce the issue that spawned that original PR, so I think the best solution would be to revert that change, and expose a config field to change the bind address. That should make it work by default for almost everyone, and when it doesnt work it can be fixed in configuration.

The other option I can see would be to change the config file in caspar to use `127.0.0.1` explicitly, but that will require all users to update that manually in their config file when updating caspar, meaning this will be discovered again and again.

**Comment by Julusian** [comment] 2023-09-04 16:06
This should be fixed with https://github.com/CasparCG/media-scanner/releases/tag/v1.2.0

**Closed by Julusian** 2023-09-04 16:06 UTC
Labels: type/bug

**Comment by andr9528** [comment] 2023-09-06 12:13
Can confirm that with version 1.2.0 of Media Scanner the issue is solved. Thanks alot :)
