### ISSUE TITLE
LOOP broken

### ISSUE THREAD

**Issue by PeterAkakpo** [CasparCG/server#839] opened 2018-02-16 04:15 UTC
In version 2.2., PLAY 1-0 video LOOP,  does not loop the video

**Comment by ronag** [comment] 2018-02-16 08:16
Could you please provide the video or another sample that has the problem?

**Comment by 5opr4ni** [comment] 2018-02-16 08:35
I have no problem with this.

**Comment by 5opr4ni** [comment] 2018-02-16 08:38
I can confirm that there is an issue here. it loops but fails after a while.

`[2018-02-16 09:34:42.911] [info]    Received message from 10.21.81.11: PLAY 1-11 "50POPAK" CUT 0 Linear RIGHT   LOOP\r\n
[2018-02-16 09:34:42.929] [info]    Sent message to 10.21.81.11:202 PLAY OK\r\n
[2018-02-16 09:35:14.398] [error]   [ffmpeg] [targa @ 0000000022544840] Packet went out of bounds
[2018-02-16 09:35:14.398] [error]   
[2018-02-16 09:35:14.402] [error]   [ffmpeg] [targa @ 0000000022544840] Packet went out of bounds
[2018-02-16 09:35:14.402] [error]   
[2018-02-16 09:35:14.406] [error]   C:\git\server2\src\modules\ffmpeg\producer\av_producer.cpp(686): Throw in function bool __cdecl caspar::ffmpeg::AVProducer::Impl::decode_frame(struct caspar::ffmpeg::Decoder &)
[2018-02-16 09:35:14.406] [error]   Dynamic exception type: class boost::exception_detail::clone_impl<struct caspar::ffmpeg::ffmpeg_error_t>
[2018-02-16 09:35:14.406] [error]   [struct boost::errinfo_api_function_ * __ptr64] = avcodec_send_packet(decoder.ctx.get(), decoder.input.front().get())
[2018-02-16 09:35:14.406] [error]   [struct boost::errinfo_errno_ * __ptr64] = 1094995529, "Unknown error"
[2018-02-16 09:35:14.406] [error]   [struct caspar::tag_stacktrace_info * __ptr64] =  0# ILT+91605(?_RethrowUserException_ExceptionHolderdetailsConcurrencyQEAAXXZ) in casparcg
[2018-02-16 09:35:14.406] [error]    1# ILT+232505(??1CefPrintJobCallbackUEAAXZ) in casparcg
[2018-02-16 09:35:14.406] [error]    2# std::make_shared<boost::any,std::shared_ptr<caspar::accelerator::ogl::buffer> > at c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.12.25827\include\memory:1918
[2018-02-16 09:35:14.406] [error]    3# std::move<<lambda_41b10fc226d36e7eaae98a6c6f9b5fea> & __ptr64> at c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.12.25827\include\type_traits:1552
[2018-02-16 09:35:14.406] [error]    4# tbb::interface7::internal::task_arena_base::internal_current_slot in tbb
[2018-02-16 09:35:14.406] [error]    5# std::move<boost::coroutines::push_coroutine<void> * __ptr64 & __ptr64> in casparcg
[2018-02-16 09:35:14.406] [error]    6# tbb::interface7::internal::task_arena_base::internal_current_slot in tbb
[2018-02-16 09:35:14.406] [error]    7# boost::asio::detail::op_queue_access::next<boost::asio::detail::scheduler_operation> in casparcg
[2018-02-16 09:35:14.406] [error]    8# tbb::interface7::internal::task_arena_base::internal_current_slot in tbb
[2018-02-16 09:35:14.406] [error]    9# boost::enable_current_exception<boost::unknown_exception> in casparcg
[2018-02-16 09:35:14.406] [error]   10# tbb::interface5::internal::concurrent_unordered_base<tbb::interface5::concurrent_unordered_map_traits<unsigned __int64,tbb::concurrent_bounded_queue<std::shared_ptr<caspar::accelerator::ogl::texture>,tbb::cache_aligned_allocator<std::shared_ptr<caspar::accelerator::ogl::texture> > >,tbb::interface5::internal::hash_compare<unsigned __int64,tbb::tbb_hash<unsigned __int64>,std::equal_to<unsigned __int64> >,tbb::tbb_allocator<std::pair<unsigned __int64 const ,tbb::concurrent_bounded_queue<std::shared_ptr<caspar::accelerator::ogl::texture>,tbb::cache_aligned_allocator<std::shared_ptr<caspar::accelerator::ogl::texture> > > > >,0> >::internal_insert<std::pair<unsigned __int64 const ,tbb::concurrent_bounded_queue<std::shared_ptr<caspar::accelerator::ogl::texture>,tbb::cache_aligned_allocator<std::shared_ptr<caspar::accelerator::ogl::texture> > > > >
[2018-02-16 09:35:25.846] [info]    Received message from 10.21.81.11: STOP 1-11\r\n
[2018-02-16 09:35:25.846] [info]    Sent message to 10.21.81.11:202 STOP OK\r\n
[2018-02-16 09:35:25.862] [info]    ffmpeg[d:/caspar/_MEDIA/50pOpak.mov|47/250] Destroyed.
[2018-02-16 09:35:26.639] [info]    Received message from 10.21.81.11: PLAY 1-11 "50POPAK" CUT 0 Linear RIGHT   LOOP\r\n
[2018-02-16 09:35:26.653] [info]    Sent message to 10.21.81.11:202 PLAY OK\r\n
[2018-02-16 09:35:27.015] [error]   [ffmpeg] [targa @ 0000000022544840] Packet went out of bounds
[2018-02-16 09:35:27.015] [error]   
[2018-02-16 09:35:27.020] [error]   [ffmpeg] [targa @ 0000000022544840] Packet went out of bounds
[2018-02-16 09:35:27.020] [error]   
[2018-02-16 09:35:27.021] [error]   C:\git\server2\src\modules\ffmpeg\producer\av_producer.cpp(686): Throw in function bool __cdecl caspar::ffmpeg::AVProducer::Impl::decode_frame(struct caspar::ffmpeg::Decoder &)
[2018-02-16 09:35:27.021] [error]   Dynamic exception type: class boost::exception_detail::clone_impl<struct caspar::ffmpeg::ffmpeg_error_t>
[2018-02-16 09:35:27.021] [error]   [struct boost::errinfo_api_function_ * __ptr64] = avcodec_send_packet(decoder.ctx.get(), decoder.input.front().get())
[2018-02-16 09:35:27.021] [error]   [struct boost::errinfo_errno_ * __ptr64] = 1094995529, "Unknown error"
[2018-02-16 09:35:27.021] [error]   [struct caspar::tag_stacktrace_info * __ptr64] =  0# ILT+91605(?_RethrowUserException_ExceptionHolderdetailsConcurrencyQEAAXXZ) in casparcg
[2018-02-16 09:35:27.021] [error]    1# ILT+232505(??1CefPrintJobCallbackUEAAXZ) in casparcg
[2018-02-16 09:35:27.021] [error]    2# std::make_shared<boost::any,std::shared_ptr<caspar::accelerator::ogl::buffer> > at c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.12.25827\include\memory:1918
[2018-02-16 09:35:27.021] [error]    3# std::move<<lambda_41b10fc226d36e7eaae98a6c6f9b5fea> & __ptr64> at c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.12.25827\include\type_traits:1552
[2018-02-16 09:35:27.021] [error]    4# tbb::interface7::internal::task_arena_base::internal_current_slot in tbb
[2018-02-16 09:35:27.021] [error]    5# std::move<boost::coroutines::push_coroutine<void> * __ptr64 & __ptr64> in casparcg
[2018-02-16 09:35:27.021] [error]    6# tbb::interface7::internal::task_arena_base::internal_current_slot in tbb
[2018-02-16 09:35:27.021] [error]    7# boost::asio::detail::op_queue_access::next<boost::asio::detail::scheduler_operation> in casparcg
[2018-02-16 09:35:27.021] [error]    8# tbb::interface7::internal::task_arena_base::internal_current_slot in tbb
[2018-02-16 09:35:27.021] [error]    9# boost::enable_current_exception<boost::unknown_exception> in casparcg
[2018-02-16 09:35:27.021] [error]   10# tbb::interface5::internal::concurrent_unordered_base<tbb::interface5::concurrent_unordered_map_traits<unsigned __int64,tbb::concurrent_bounded_queue<std::shared_ptr<caspar::accelerator::ogl::texture>,tbb::cache_aligned_allocator<std::shared_ptr<caspar::accelerator::ogl::texture> > >,tbb::interface5::internal::hash_compare<unsigned __int64,tbb::tbb_hash<unsigned __int64>,std::equal_to<unsigned __int64> >,tbb::tbb_allocator<std::pair<unsigned __int64 const ,tbb::concurrent_bounded_queue<std::shared_ptr<caspar::accelerator::ogl::texture>,tbb::cache_aligned_allocator<std::shared_ptr<caspar::accelerator::ogl::texture> > > > >,0> >::internal_insert<std::pair<unsigned __int64 const ,tbb::concurrent_bounded_queue<std::shared_ptr<caspar::accelerator::ogl::texture>,tbb::cache_aligned_allocator<std::shared_ptr<caspar::accelerator::ogl::texture> > > > >
`

**Comment by 5opr4ni** [comment] 2018-02-16 08:48
It works with a 1080i5000 with audio but fails with an p5000 with no audio.
If the audio has any relevance, I have to find out.

**Comment by 5opr4ni** [comment] 2018-02-16 08:52
Can't really find why. Now it suddenly works! Have to do more tests.

**Comment by ronag** [comment] 2018-02-16 09:54
@5opr4ni that seems to be an issue with the file or an ffmepg bug, not related to caspar loop.

**Comment by ronag** [comment] 2018-02-16 09:55
@PeterAkakpo please help us reproduce your problem.

**Comment by PeterAkakpo** [comment] 2018-02-18 16:13
this is one of the files that is not looping
[as.zip](https://github.com/CasparCG/server/files/1734860/as.zip)

**Comment by ronag** [comment] 2018-02-18 16:24
The problem here is that the video is much longer than the expected duration so it basically is stuck trying to get more audio. Not sure how to resolve this:

1. Keep playing without audio.
2. Just stop at the expected duration

**Comment by ronag** [comment] 2018-02-18 16:41
weird file, but fixed with 2.

**Closed by ronag** 2018-02-18 16:41 UTC
Labels: bug, on hold
