### ISSUE TITLE
Non-standard resolution media causes OGL error tailspin

### ISSUE THREAD

**Issue by TomKaltz** [CasparCG/server#878] opened 2018-02-26 02:07 UTC
https://drive.google.com/open?id=1UxjYHIC1n5RxTzLCxVPDYTgveoyK8jx5

This file sends the server into a tailspin of OGL errors.  This should be guarded against somehow.

```
[2018-02-25 21:00:58.077] [info]    Received message from Console: play 1-1 asg2\r\n
[2018-02-25 21:00:58.110] [error]   OpenGL Error: 1282 0000000062585238
[2018-02-25 21:00:58.110] [error]   OpenGL Error: 1282 0000000062585238
[2018-02-25 21:00:58.110] [error]   OpenGL Error: 1282 0000000062585238
[2018-02-25 21:00:58.127] [error]   OpenGL Error: 1282 0000000062585238
[2018-02-25 21:00:58.127] [error]   OpenGL Error: 1282 0000000062585238
[2018-02-25 21:00:58.127] [error]   OpenGL Error: 1282 0000000062585238
[2018-02-25 21:00:58.133] [info]    ffmpeg[media/INCEPTION.mov|2246/532679] Destroyed.
[2018-02-25 21:00:58.127] [error]   C:\git\server3\src\common\gl\gl_check.cpp(59): Throw in function void __cdecl caspar::gl::SMFL_GLCheckError(const class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,const char *,const char *,unsigned int)
[2018-02-25 21:00:58.127] [error]   Dynamic exception type: class boost::exception_detail::clone_impl<struct caspar::gl::ogl_invalid_operation>
[2018-02-25 21:00:58.127] [error]   [struct caspar::tag_error_info * __ptr64] = GL_INVALID_OPERATION
[2018-02-25 21:00:58.127] [error]   [struct caspar::tag_msg_info * __ptr64] = the specified operation is not allowed in the current state
[2018-02-25 21:00:58.127] [error]   [struct caspar::tag_stacktrace_info * __ptr64] =  0# 0x000000013FD5793E in casparcg
[2018-02-25 21:00:58.127] [error]    1# 0x000000013FD79FD0 in casparcg
[2018-02-25 21:00:58.127] [error]    2# 0x000000013FDDDE96 in casparcg
[2018-02-25 21:00:58.127] [error]    3# 0x000000013FDB230C in casparcg
[2018-02-25 21:00:58.127] [error]    4# 0x000000013FDA146C in casparcg
[2018-02-25 21:00:58.127] [error]    5# 0x000000013FDA5B17 in casparcg
[2018-02-25 21:00:58.127] [error]    6# 0x000000013FDA560E in casparcg
[2018-02-25 21:00:58.127] [error]    7# 0x000000013FD8FC97 in casparcg
[2018-02-25 21:00:58.127] [error]    8# 0x000000013FDAA88A in casparcg
[2018-02-25 21:00:58.127] [error]    9# 0x000000013FD74416 in casparcg
[2018-02-25 21:00:58.127] [error]   10# 0x000000013FDA61FF in casparcg
[2018-02-25 21:00:58.127] [error]   11# 0x000000013FD53CA9 in casparcg
[2018-02-25 21:00:58.127] [error]   12# crt_at_quick_exit in ucrtbase
[2018-02-25 21:00:58.127] [error]   13# BaseThreadInitThunk in kernel32
[2018-02-25 21:00:58.127] [error]   14# RtlUserThreadStart in ntdll
[2018-02-25 21:00:58.127] [error]   
[2018-02-25 21:00:58.127] [error]   
[2018-02-25 21:00:58.165] [error]   OpenGL Error: 1282 0000000062585238
[2018-02-25 21:00:58.165] [error]   OpenGL Error: 1282 0000000062585238
[2018-02-25 21:00:58.165] [error]   OpenGL Error: 1282 0000000062585238
[2018-02-25 21:00:58.165] [error]   Dynamic exception type: class std::future_error
[2018-02-25 21:00:58.165] [error]   std::exception::what: no state
[2018-02-25 21:00:58.165] [error]   
[2018-02-25 21:00:58.166] [error]   OpenGL Error: 1282 0000000062585238
[2018-02-25 21:00:58.166] [error]   OpenGL Error: 1282 0000000062585238
[2018-02-25 21:00:58.166] [error]   OpenGL Error: 1282 0000000062585238
[2018-02-25 21:00:58.166] [error]   Dynamic exception type: class std::future_error
[2018-02-25 21:00:58.166] [error]   std::exception::what: no state
[2018-02-25 21:00:58.166] [error]   
[2018-02-25 21:00:58.167] [error]   OpenGL Error: 1282 0000000062585238
[2018-02-25 21:00:58.167] [error]   OpenGL Error: 1282 0000000062585238
[2018-02-25 21:00:58.167] [error]   Dynamic exception type: class std::future_error
[2018-02-25 21:00:58.167] [error]   std::exception::what: no state
[2018-02-25 21:00:58.167] [error]   
[2018-02-25 21:00:58.167] [error]   OpenGL Error: 1282 0000000062585238
[2018-02-25 21:00:58.167] [error]   OpenGL Error: 1282 0000000062585238
[2018-02-25 21:00:58.167] [error]   OpenGL Error: 1282 0000000062585238
[2018-02-25 21:00:58.167] [error]   OpenGL Error: 1282 0000000062585238
[2018-02-25 21:00:58.167] [error]   Dynamic exception type: class std::future_error
[2018-02-25 21:00:58.167] [error]   std::exception::what: no state
[2018-02-25 21:00:58.167] [error]   
[2018-02-25 21:00:58.168] [error]   OpenGL Error: 1282 0000000062585238
[2018-02-25 21:00:58.168] [error]   OpenGL Error: 1282 0000000062585238
[2018-02-25 21:00:58.168] [error]   Dynamic exception type: class std::future_error
[2018-02-25 21:00:58.168] [error]   std::exception::what: no state
[2018-02-25 21:00:58.168] [error]   
[2018-02-25 21:00:58.168] [error]   OpenGL Error: 1282 0000000062585238
[2018-02-25 21:00:58.169] [error]   OpenGL Error: 1282 0000000062585238
[2018-02-25 21:00:58.169] [error]   OpenGL Error: 1282 0000000062585238
[2018-02-25 21:00:58.169] [error]   Dynamic exception type: class std::future_error
[2018-02-25 21:00:58.169] [error]   std::exception::what: no state
[2018-02-25 21:00:58.169] [error]   
[2018-02-25 21:00:58.169] [error]   OpenGL Error: 1282 0000000062585238
[2018-02-25 21:00:58.169] [error]   OpenGL Error: 1282 0000000062585238
[2018-02-25 21:00:58.169] [error]   OpenGL Error: 1282 0000000062585238
[2018-02-25 21:00:58.169] [error]   OpenGL Error: 1282 0000000062585238
[2018-02-25 21:00:58.170] [error]   Dynamic exception type: class std::future_error
[2018-02-25 21:00:58.170] [error]   std::exception::what: no state
[2018-02-25 21:00:58.170] [error]   
[2018-02-25 21:00:58.170] [error]   OpenGL Error: 1282 0000000062585238
[2018-02-25 21:00:58.170] [error]   OpenGL Error: 1282 0000000062585238
[2018-02-25 21:00:58.170] [error]   Dynamic exception type: class std::future_error
[2018-02-25 21:00:58.170] [error]   std::exception::what: no state
[2018-02-25 21:00:58.170] [error]   
[2018-02-25 21:00:58.170] [error]   OpenGL Error: 1282 0000000062585238
[2018-02-25 21:00:58.171] [error]   OpenGL Error: 1282 0000000062585238
[2018-02-25 21:00:58.171] [error]   OpenGL Error: 1282 0000000062585238
[2018-02-25 21:00:58.171] [error]   Dynamic exception type: class std::future_error
[2018-02-25 21:00:58.171] [error]   std::exception::what: no state
[2018-02-25 21:00:58.171] [error]   
[2018-02-25 21:00:58.171] [error]   OpenGL Error: 1282 0000000062585238
[2018-02-25 21:00:58.171] [error]   Dynamic exception type: class std::future_error
[2018-02-25 21:00:58.171] [error]   std::exception::what: no state
[2018-02-25 21:00:58.171] [error]   
[2018-02-25 21:00:58.171] [error]   Dynamic exception type: class std::future_error
[2018-02-25 21:00:58.171] [error]   std::exception::what: no state
[2018-02-25 21:00:58.171] [error]   
[2018-02-25 21:00:58.171] [error]   Dynamic exception type: class std::future_error
[2018-02-25 21:00:58.171] [error]   std::exception::what: no state
[2018-02-25 21:00:58.171] [error]   
[2018-02-25 21:00:58.171] [error]   Dynamic exception type: class std::future_error
[2018-02-25 21:00:58.171] [error]   std::exception::what: no state
[2018-02-25 21:00:58.171] [error]   
[2018-02-25 21:00:58.172] [error]   Dynamic exception type: class std::future_error
[2018-02-25 21:00:58.172] [error]   std::exception::what: no state
[2018-02-25 21:00:58.172] [error]   
[2018-02-25 21:00:58.172] [error]   Dynamic exception type: class std::future_error
[2018-02-25 21:00:58.172] [error]   std::exception::what: no state
[2018-02-25 21:00:58.172] [error]   
[2018-02-25 21:00:58.172] [error]   Dynamic exception type: class std::future_error
[2018-02-25 21:00:58.172] [error]   std::exception::what: no state
```

**Comment by baltedewit** [comment] 2018-02-26 17:11
Same issue reproduced on linux using http://media.streamone.net/hlslive/account=gCRIPoIbRB0W/livestream=v6IEh8-CC9YW/v6IEh8-CC9YW.m3u8 (hls live) as input.

**Comment by baltedewit** [comment] 2018-03-04 06:54
Note, as a workaround you can use a VF filter: `PLAY 1-10 media VF scale=x:y`

**Comment by premultiply** [comment] 2018-03-04 10:46
So maybe the problem here is the requiered two-dimensional crop to get the active picture from the codec picture.

**Comment by ronag** [comment] 2018-03-04 10:51
There is some kind of limitation if OGL in terms of dimensions (weird). The fix is 1 hack around the OGL issue, 2 hack in ffmpeg by adding an auto scale filter which scales it to an appropriate dimension.

**Comment by ronag** [comment] 2018-03-04 10:52
We should probably also fix the error tailspin.

**Comment by pkeuter** [comment] 2018-03-04 11:32
I don't see any OGL errors. Is this Linux only?

What I do see when playing the file by @TomKaltz is this: 
![image](https://user-images.githubusercontent.com/433441/36945030-f6cee6ac-1fa7-11e8-8da6-e6dccaef2904.png)

I have absolutely no idea why this is happening, am I the only one?

**Comment by ronag** [comment] 2018-03-04 11:45
Please make sure you have the latest GPU drivers when testing this.

**Comment by saltomodules** [comment] 2018-03-19 10:17
Perhaps of use is that this looks to be related to an earlier issue which was closed by @ronag with the request for further testing on 2.2: https://github.com/CasparCG/server/issues/632

We've run the same tests (see for details the issue mentioned above) on `2.2.0.4 529f94a7 Beta 1 ` and it looks like casparcg still fails to play files that do no have a width that is a multiple of 8
(for heights a multiple of 2 is fine)

We can confirm that (while 2.1 failed with an error) 2.2 goes indeed into an opengl error tailspin which exhausts memory in no time.

system information:
win 7 x64
gtx 660
nvidia driver 391.01 (latest)

test files are uploaded here:
https://www.dropbox.com/sh/pjkj1cbvgqiu3d9/AAAuzJnhrlcXozZjo8w8-3CQa?dl=0

**Comment by MauriceVeraart** [comment] 2018-04-06 08:30
seeing this behavior too
with some tests I found out this error happens when the horizontal resolution
is not dividable by 16 maybe this can be used as a filter to not try to play the file.

**Comment by ronag** [comment] 2018-04-06 08:35
It might go as far as not dividable by 32 with AVX512

**Comment by ronag** [comment] 2018-07-18 10:18
Needs to be dividable by 4. Fixed in FFMPEG producer. Might need a better fix in the future in the OGL code.

**Closed by ronag** 2018-07-18 10:18 UTC
Labels: PR wanted, bug, ffmpeg-producer

**Comment by drakmor** [comment] 2018-07-18 12:35
http://media.streamone.net/hlslive/account=gCRIPoIbRB0W/livestream=v6IEh8-CC9YW/v6IEh8-CC9YW.m3u8 -   Stream #0:1: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 852x480 [SAR 1:1 DAR 71:40], 25 fps, 25 tbr, 90k tbn, 50 tbc

852/4=213 dividable by 4 but not work

**Comment by ronag** [comment] 2018-07-18 12:40
Probably depends on drivers as well. I've changed it to 16.

**Comment by ronag** [comment] 2018-07-18 12:45
Ah, a better fix is to set `GL_UNPACK_ALIGNMENT`

**Comment by saltomodules** [comment] 2018-07-27 21:05
Retested with all file variations from the test file set posted above. All variations now work. Nice!
