### ISSUE TITLE
2.2.0 stable - Memory leak

### ISSUE THREAD

**Issue by RTVA** [CasparCG/server#1158] opened 2019-01-14 16:46 UTC
### Current behaviour
Memory Leak ... The server is not doing anything, but the memory is growing slowly but continuously... after a few days of operation I had a system memory failure on a 16GB PC ;)

### Steps to reproduce
1. Start [CasparCG server 2.2.0 stable](https://casparcgforum.org/t/release-casparcg-server-2-2-0-stable/1252)
2. look at memory usage

### Environment
* Server version: [CasparCG server 2.2.0 stable , default config]
* Operating system: [Windows 10 64 bits]

**Comment by Julusian** [comment] 2019-01-14 16:51
What consumers are you using? Can you post your config file?

**Comment by petterreinholdtsen** [comment] 2019-01-14 16:53
The environment is said to be the default config.  I guess it means https://github.com/CasparCG/server/blob/master/src/shell/casparcg.config is used.

**Comment by RTVA** [comment] 2019-01-14 16:54
Hi Julusian,

Is the default config... 
`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <paths>
    <media-path>media/</media-path>
    <log-path>log/</log-path>
    <data-path>data/</data-path>
    <template-path>template/</template-path>
    <font-path>font/</font-path>
  </paths>
  <lock-clear-phrase>secret</lock-clear-phrase>
  <channels>
    <channel>
      <video-mode>720p5000</video-mode>
      <consumers>
        <screen/>
        <system-audio/>
      </consumers>
    </channel>
  </channels>
  <controllers>
    <tcp>
      <port>5250</port>
      <protocol>AMCP</protocol>
    </tcp>
  </controllers>
  <amcp>
    <media-server>
      <host>localhost</host>
      <port>8000</port>
    </media-server>
  </amcp>
</configuration>`

**Comment by Julusian** [comment] 2019-01-14 16:55
I suspect this is a duplicate of #946 then

**Comment by RTVA** [comment] 2019-01-14 17:04
Yes ...
It seems to be the `<system-audio />`
After commenting on this line, there is no memory leak !!!

**Comment by Julusian** [comment] 2019-01-14 18:41
ok, Im going to close this in favour of the existing issue for it

**Closed by Julusian** 2019-01-14 18:41 UTC
