### ISSUE TITLE
[Feature Request] Uptime

### ISSUE THREAD

**Issue by jimmn** [CasparCG/server#327] opened 2014-11-29 16:07 UTC
Would it be possible to add an up-time counter to the server?
With this, you could periodically poll the counter to see if there had been a restart due to a crash, or a power outage etc.

Could be part of the Version command, or have it's own AMCP command.

**Comment by Julusian** [comment] 2019-01-13 23:34
Duplicate of #94

**Closed by Julusian** 2019-01-13 23:34 UTC
