### ISSUE TITLE
Segfaults on STOP since 20fc0b9

### ISSUE THREAD

**Issue by saltomodules** [CasparCG/server#1154] opened 2019-01-09 07:54 UTC
### Expected behaviour
Segfaults do not occur under normal usage

### Current behaviour
Since https://github.com/CasparCG/server/commit/20fc0b90f32b1c5c7efc196d195b891d97090448 segfaults occur regularly after STOP commands on our 24/7 test server. Before this commit this particular behavior doesn't seem to be present.

On the console it looks like this:
```
[2019-01-09 08:35:55.189] [info]    Received message from 192.168.100.103: STOP 4-4\r\n
[2019-01-09 08:35:55.189] [debug]   Executing command: STOP
[2019-01-09 08:35:55.189] [debug]   Executed command (0s): STOP
[2019-01-09 08:35:55.189] [debug]   ffmpeg[2018/01/19/5a620604746e2207d5def464_audio.mp4|8959/8959] Destroying on asynchronous destruction thread.
[2019-01-09 08:35:55.189] [info]    Sent message to 192.168.100.103:202 STOP OK\r\n
[2019-01-09 08:35:55.189] [info]    ffmpeg[2018/01/19/5a620604746e2207d5def464_audio.mp4|8959/8959] Destroyed.
Aborted (core dumped)
```

This issue is in addition to the segfaults occurring on `LOADBG` reported under https://github.com/CasparCG/server/issues/1128

----

### Steps to reproduce
1. We just let the server run while regularly loading, starting and stopping video and audio only clips on five separate channels. Intervals between segfaults are often just a few minutes to at most one day. 

### Environment
    CasparCG Server version:
    from 2.2.0 20fc0b90f Beta 11 to 2.3.0 d1952973e Dev
    video-mode 1080i5000, PAL on some channels    

    Operating system:
    Ubuntu 18.04

    Graphics driver:
    Nvidia 390.42 (for GTX1050)

    Decklink drivers:
    Blackmagic Design BlackmagicIO driver 10.10a3

**Comment by Julusian** [comment] 2019-01-09 11:07
I'm not sure what could be special about that commit to cause this. If it wasn't for that I would have suspected this of being a duplicate of #1128, with the issue being in the ffmpeg producer destruction code.

**Comment by saltomodules** [comment] 2019-03-26 20:43
Issue https://github.com/CasparCG/server/issues/1128 is fixed by https://github.com/CasparCG/server/commit/f56cca7f3b63eb1ef2ee0910ec781b34387b85d3. However, the `STOP` segfaults keep occuring which makes it look more certain we're dealing with a separate issue here.

We also ran some more duration tests with 'before' and 'after' commits to make sure https://github.com/CasparCG/server/commit/20fc0b90f32b1c5c7efc196d195b891d97090448 is the commit this issue starts occuring and by the looks of it that seems to be definitely the case.

Could it be that code in this commit is indirectly influencing some unguarded shared memory leading to a higher probability of race condition conflicts or something in that direction?

**Comment by saltomodules** [comment] 2019-03-29 15:39
Backtraces from gdb show these segfaults on `STOP` do always end up at line 81 in `draw_frame.cpp` before going to `libtbbmalloc.so.2`

Two examples following slightly different pathways:

```
Thread 33 "stage 3" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f903a226700 (LWP 22432)]
0x00007f908539d745 in ?? () from /usr/lib/x86_64-linux-gnu/libtbbmalloc.so.2
(gdb) bt
#0  0x00007f908539d745 in  () at /usr/lib/x86_64-linux-gnu/libtbbmalloc.so.2
#1  0x00007f908539d7ff in  () at /usr/lib/x86_64-linux-gnu/libtbbmalloc.so.2
#2  0x00007f908539f418 in  () at /usr/lib/x86_64-linux-gnu/libtbbmalloc.so.2
#3  0x00007f90853a0006 in scalable_malloc () at /usr/lib/x86_64-linux-gnu/libtbbmalloc.so.2
#4  0x00007f908518d629 in operator new(unsigned long) () at /usr/lib/x86_64-linux-gnu/libtbbmalloc_proxy.so.2
#5  0x000055adead5a0be in caspar::core::draw_frame::draw_frame(caspar::core::draw_frame const&) (this=0x7f8ff2d030e8, other=...) at /home/salto/code/casparcg-server-master/src/core/frame/draw_frame.cpp:81
#6  0x000055adead5a178 in std::_Construct<caspar::core::draw_frame, caspar::core::draw_frame const&>(caspar::core::draw_frame*, caspar::core::draw_frame const&) (__p=<optimized out>) at /usr/include/c++/7/bits/stl_construct.h:75
#7  0x000055adead5a178 in std::__uninitialized_copy<false>::__uninit_copy<__gnu_cxx::__normal_iterator<caspar::core::draw_frame const*, std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> > >, caspar::core::draw_frame*>(__gnu_cxx::__normal_iterator<caspar::core::draw_frame const*, std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> > >, __gnu_cxx::__normal_iterator<caspar::core::draw_frame const*, std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> > >, caspar::core::draw_frame*) (__result=<optimized out>, __last=..., __first=
    {impl_ = std::unique_ptr<caspar::core::draw_frame::impl> = {get() = 0x7f8ff2d2d300}}) at /usr/include/c++/7/bits/stl_uninitialized.h:83
#8  0x000055adead5a178 in std::uninitialized_copy<__gnu_cxx::__normal_iterator<caspar::core::draw_frame const*, std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> > >, caspar::core::draw_frame*>(__gnu_cxx::__normal_iterator<caspar::core::draw_frame const*, std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> > >, __gnu_cxx::__normal_iterator<caspar::core::draw_frame const*, std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> > >, caspar::core::draw_frame*) (__result=<optimized out>, __last=..., __first=...)
    at /usr/include/c++/7/bits/stl_uninitialized.h:134
#9  0x000055adead5a178 in std::__uninitialized_copy_a<__gnu_cxx::__normal_iterator<caspar::core::draw_frame const*, std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> > >, caspar::core::draw_frame*, caspar::core::draw_frame>(__gnu_cxx::__normal_iterator<caspar::core::draw_frame const*, std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> > >, __gnu_cxx::__normal_iterator<caspar::core::draw_frame const*, std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> > >, caspar::core::draw_frame*, std::allocator<caspar::core::draw_frame>&) (__result=<optimized out>, __last=..., __first=...) at /usr/include/c++/7/bits/stl_uninitialized.h:289
#10 0x000055adead5a178 in std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> >::vector(std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> > const&) (__x=..., this=<synthetic pointer>) at /usr/include/c++/7/bits/stl_vector.h:331
#11 0x000055adead5a178 in boost::variant<boost::blank, caspar::core::const_frame, std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> > >::assigner::assign_impl<std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> >, boost::variant<boost::blank, caspar::core::const_frame, std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> > >::has_fallback_type_>(std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> > const&, mpl_::bool_<false>, mpl_::bool_<true>, boost::variant<boost::blank, caspar::core::const_frame, std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> > >::has_fallback_type_) const (rhs_content=..., this=<synthetic pointer>) at /opt/boost/include/boost/variant/variant.hpp:1946
#12 0x000055adead5a178 in boost::variant<boost::blank, caspar::core::const_frame, std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> > >::assigner::internal_visit<std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> > >(std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> > const&, int) const (rhs_content=..., this=<synthetic pointer>) at /opt/boost/include/boost/variant/variant.hpp:2026
#13 0x000055adead5a178 in boost::detail::variant::visitation_impl_invoke_impl<boost::variant<boost::blank, caspar::core::const_frame, std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> > >::assigner, void const*, std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> > >(int, boost::variant<boost::blank, caspar::core::const_frame, std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> > >::assigner&, void const*, std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> >*, mpl_::bool_<true>) (storage=<optimized out>, visitor=<synthetic pointer>...) at /opt/boost/include/boost/variant/detail/visitation_impl.hpp:114
#14 0x000055adead5a178 in boost::detail::variant::visitation_impl_invoke<boost::variant<boost::blank, caspar::core::const_frame, std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> > >::assigner, void const*, std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> >, boost::variant<boost::blank, caspar::core::const_frame, std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> > >::has_fallback_type_>(int, boost::variant<boost::blank, caspar::core::const_frame, std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> > >::assigner&, void const*, std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> >*, boost::variant<boost::blank, caspar::core::const_frame, std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> > >::has_fallback_type_, int) (internal_which=<optimized out>, t=0x0, storage=<optimized out>, visitor=<synthetic pointer>...) at /opt/boost/include/boost/variant/detail/visitation_impl.hpp:154
#15 0x000055adead5a178 in boost::detail::variant::visitation_impl<mpl_::int_<0>, boost::detail::variant::visitation_impl_step<boost::mpl::l_iter<boost::mpl::l_item<mpl_::long_<3l>, boost::blank, boost::mpl::l_item<mpl_::long_<2l>, caspar::core::const_frame, boost::mpl::l_item<mpl_::long_<1l>, std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> >, boost::mpl::l_end> > > >, boost::mpl::l_iter<boost::mpl::l_end> >, boost::variant<boost::blank, caspar::core::const_frame, std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> > >::assigner, void const*, boost::variant<boost::blank, caspar::core::const_frame, std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> > >::has_fallback_type_>(int, int, boost::variant<boost::blank, caspar::core::const_frame, std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> > >::assigner&, void const*, mpl_::bool_<false>, boost::variant<boost::blank, caspar::core::const_frame, std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> > >::has_fallback_type_, mpl_::int_<0>*, boost::detail::variant::visitation_impl_step<boost::mpl::l_iter<boost::mpl::l_item<mpl_::long_<3l>, boost::blank, boost::mpl::l_item<mpl_::long_<2l>, caspar::core::const_frame, boost::mpl::l_item<mpl_::long_<1l>, std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> >, boost::mpl::l_end> > > >, boost::mpl::l_iter<boost::mpl::l_end> >*) (no_backup_flag=..., storage=<optimized out>, visitor=<synthetic pointer>..., logical_which=<optimized out>, internal_which=<optimized out>) at /opt/boost/include/boost/variant/detail/visitation_impl.hpp:238
#16 0x000055adead5a178 in boost::variant<boost::blank, caspar::core::const_frame, std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> > >::internal_apply_visitor_impl<boost::variant<boost::blank, caspar::core::const_frame, std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> > >::assigner, void const*>(int, int, boost::variant<boost::blank, caspar::core::const_frame, std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> > >::assigner&, void const*) (storage=<optimized out>, visitor=<synthetic pointer>..., logical_which=<optimized out>, internal_which=<optimized out>) at /opt/boost/include/boost/variant/variant.hpp:2452
#17 0x000055adead5a178 in boost::variant<boost::blank, caspar::core::const_frame, std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> > >::internal_apply_visitor<boost::variant<boost::blank, caspar::core::const_frame, std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> > >::assigner>(boost::variant<boost::blank, caspar::core::const_frame, std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> > >::assigner&) const (visitor=..., this=<optimized out>) at /opt/boost/include/boost/variant/variant.hpp:2477
#18 0x000055adead5a178 in boost::variant<boost::blank, caspar::core::const_frame, std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> > >::variant_assign(boost::variant<boost::blank, caspar::core::const_frame, std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> > > const&) (rhs=..., this=0x7f8ff2d2fd00) at /opt/boost/include/boost/variant/variant.hpp:2181
#19 0x000055adead5a178 in boost::variant<boost::blank, caspar::core::const_frame, std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> > >::operator=(boost::variant<boost::blank, caspar::core::const_frame, std::vector<caspar::core::draw_frame, std::allocator<caspar::core::draw_frame> > > const&) (rhs=..., this=0x7f8ff2d2fd00) at /opt/boost/include/boost/variant/variant.hpp:2278
#20 0x000055adead5a178 in caspar::core::draw_frame::draw_frame(caspar::core::draw_frame const&) (this=0x7f903a2254e0, other=...) at /home/salto/code/casparcg-server-master/src/core/frame/draw_frame.cpp:83
#21 0x000055adead420cb in caspar::core::layer_frame::operator=(caspar::core::layer_frame const&) (this=0x7f8ff2d32a68) at /home/salto/code/casparcg-server-master/src/core/producer/stage.h:43
#22 0x000055adead420cb in caspar::core::stage::impl::operator()(caspar::core::video_format_desc const&, int, std::vector<int, std::allocator<int> >&)::{lambda()#1}::operator()() const (__closure=0x7f9041256cf8) at /home/salto/code/casparcg-server-master/src/core/producer/stage.cpp:83
#23 0x000055adead436c0 in std::__invoke_impl<std::map<int, caspar::core::layer_frame, std::less<int>, std::allocator<std::pair<int const, caspar::core::layer_frame> > >, caspar::core::stage::impl::operator()(caspar::core::video_format_desc const&, int, std::vector<int, std::allocator<int> >&)::{lambda()#1}&>(std::__invoke_other, caspar::core::stage::impl::operator()(caspar::core::video_format_desc const&, int, std::vector<int, std::allocator<int> >&)::{lambda()#1}&) (__f=...) at /usr/include/c++/7/bits/invoke.h:60
#24 0x000055adead436c0 in std::__invoke<caspar::core::stage::impl::operator()(caspar::core::video_format_desc const&, int, std::vector<int, std::allocator<int> >&)::{lambda()#1}&>(std::__invoke_result&&, (caspar::core::stage::impl::operator()(caspar::core::video_format_desc const&, int, std::vector<int, std::allocator<int> >&)::{lambda()#1}&)...) (__fn=...) at /usr/include/c++/7/bits/invoke.h:96
#25 0x000055adead436c0 in std::__future_base::_Task_state<caspar::core::stage::impl::operator()(caspar::core::video_format_desc const&, int, std::vector<int, std::allocator<int> >&)::{lambda()#1}, std::allocator<int>, std::map<int, caspar::core::layer_frame, std::less<int>, std::allocator<std::pair<int const, std::map> > > ()>::_M_run()::{lambda()#1}::operator()() const (__closure=<optimized out>) at /usr/include/c++/7/future:1421
#26 0x000055adead436c0 in std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<std::map<int, caspar::core::layer_frame, std::less<int>, std::allocator<std::pair<int const, caspar::core::layer_frame> > > >, std::__future_base::_Result_base::_Deleter>, std::__future_base::_Task_state<caspar::core::stage::impl::operator()(caspar::core::video_format_desc const&, int, std::vector<int, std::allocator<int> >&)::{lambda()#1}, std::allocator<int>, std::map<int, caspar::core::layer_frame, std::less<int>, std::allocator<std::pair<int const, caspar::core::layer_frame> > > ()>::_M_run()::{lambda()#1}, std::map<int, caspar::core::layer_frame, std::less<int>, std::allocator<std::pair<int const, caspar::core::layer_frame> > > >::operator()() const (this=0x7f903a225930) at /usr/include/c++/7/future:1339
#27 0x000055adead436c0 in std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<std::map<int, caspar::core::layer_frame, std::less<int>, std::allocator<std::pair<int const, caspar::core::layer_frame> > > >, std::__future_base::_Result_base::_Deleter>, std::__future_base::_Task_state<caspar::core::stage::impl::operator()(caspar::core::video_format_desc const&, int, std::vector<int, std::allocator<int> >&)::{lambda()#1}, std::allocator<int>, std::map<int, caspar::core::layer_frame, std::less<int>, std::allocator<std::pair<int const, caspar::core::layer_frame> > > ()>::_M_run()::{lambda()#1}, std::map<int, caspar::core::layer_frame, std::less<int>, std::allocator<std::pair<int const, caspar::core::layer_frame> > > > >::_M_invoke(std::_Any_data const&) (__functor=...)
    at /usr/include/c++/7/bits/std_function.h:302
#28 0x000055adeac8b399 in std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>::operator()() const (this=<optimized out>) at /usr/include/c++/7/bits/std_function.h:706
#29 0x000055adeac8b399 in std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*) (this=0x7f9041256cd0, __f=<optimized out>, __did_set=0x7f903a2258a7) at /usr/include/c++/7/future:561
#30 0x00007f907ecb2827 in __pthread_once_slow (once_control=0x7f9041256ce8, init_routine=0x7f9076acd760 <__once_proxy>) at pthread_once.c:116
#31 0x000055adead35534 in __gthread_once (__func=<optimized out>, __once=0x7f9041256ce8) at /usr/include/x86_64-linux-gnu/c++/7/bits/gthr-default.h:699
#32 0x000055adead35534 in std::call_once<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*>(std::once_flag&, void (std::__future_base::_State_baseV2::*&&)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*&&, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*&&, bool*&&) (__f=
    @0x7f903a2258c0: (void (std::__future_base::_State_baseV2::*)(std::__future_base::_State_baseV2 * const, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter>()> *, bool *)) 0x55adeac8b370 <std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)>, __once=...) at /usr/include/c++/7/mutex:684
#33 0x000055adead35534 in std::__future_base::_State_baseV2::_M_set_result(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>, bool) (this=0x7f9041256cd0, __res=..., __ignore_failure=false) at /usr/include/c++/7/future:401
#34 0x000055adead3a0a5 in std::__future_base::_Task_state<caspar::core::stage::impl::operator()(caspar::core::video_format_desc const&, int, std::vector<int, std::allocator<int> >&)::{lambda()#1}, std::allocator<int>, std::map<int, caspar::core::layer_frame, std::less<int>, std::allocator<std::pair<int const, std::map> > > ()>::_M_run() (this=<optimized out>) at /usr/include/c++/7/future:1423
#35 0x000055adead3a0a5 in std::packaged_task<std::map<int, caspar::core::layer_frame, std::less<int>, std::allocator<std::pair<int const, caspar::core::layer_frame> > > ()>::operator()() (this=<optimized out>) at /usr/include/c++/7/future:1556
#36 0x000055adead3a0a5 in auto caspar::executor::begin_invoke<caspar::core::stage::impl::operator()(caspar::core::video_format_desc const&, int, std::vector<int, std::allocator<int> >&)::{lambda()#1}>(caspar::core::stage::impl::operator()(caspar::core::video_format_desc const&, int, std::vector<int, std::allocator<int> >&)::{lambda()#1}&&)::{lambda()#1}::operator()() (__closure=<optimized out>) at /home/salto/code/casparcg-server-master/src/core/../common/executor.h:73
#37 0x000055adead3a0a5 in std::_Function_handler<void (), auto caspar::executor::begin_invoke<caspar::core::stage::impl::operator()(caspar::core::video_format_desc const&, int, std::vector<int, std::allocator<int> >&)::{lambda()#1}>(caspar::core::stage::impl::operator()(caspar::core::video_format_desc const&, int, std::vector<int, std::allocator<int> >&)::{lambda()#1}&&)::{lambda()#1}>::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/7/bits/std_function.h:316
#38 0x000055adead1f72f in std::function<void ()>::operator()() const (this=0x7f903a2259d0) at /usr/include/c++/7/bits/std_function.h:706
#39 0x000055adead1f72f in caspar::executor::run() (this=0x7f9042b535a0) at /home/salto/code/casparcg-server-master/src/core/../common/executor.h:142
#40 0x00007f9076ace57f in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#41 0x00007f907ecaa6db in start_thread (arg=0x7f903a226700) at pthread_create.c:463
#42 0x00007f907652988f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

```
Thread 28 "stage 3" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f881b490700 (LWP 9672)]
0x00007f8866384745 in ?? () from /usr/lib/x86_64-linux-gnu/libtbbmalloc.so.2
(gdb) bt
#0  0x00007f8866384745 in  () at /usr/lib/x86_64-linux-gnu/libtbbmalloc.so.2
#1  0x00007f88663847ff in  () at /usr/lib/x86_64-linux-gnu/libtbbmalloc.so.2
#2  0x00007f8866386418 in  () at /usr/lib/x86_64-linux-gnu/libtbbmalloc.so.2
#3  0x00007f8866387006 in scalable_malloc () at /usr/lib/x86_64-linux-gnu/libtbbmalloc.so.2
#4  0x00007f8866174629 in operator new(unsigned long) () at /usr/lib/x86_64-linux-gnu/libtbbmalloc_proxy.so.2
#5  0x0000556a81c150be in caspar::core::draw_frame::draw_frame(caspar::core::draw_frame const&) (this=0x7f881b48f4e0, other=...) at /home/salto/code/casparcg-server-master/src/core/frame/draw_frame.cpp:81
#6  0x0000556a81bfd0cb in caspar::core::layer_frame::operator=(caspar::core::layer_frame const&) (this=0x7f87f272fee8) at /home/salto/code/casparcg-server-master/src/core/producer/stage.h:43
#7  0x0000556a81bfd0cb in caspar::core::stage::impl::operator()(caspar::core::video_format_desc const&, int, std::vector<int, std::allocator<int> >&)::{lambda()#1}::operator()() const (__closure=0x7f88214ddfd8) at /home/salto/code/casparcg-server-master/src/core/producer/stage.cpp:83
#8  0x0000556a81bfe6c0 in std::__invoke_impl<std::map<int, caspar::core::layer_frame, std::less<int>, std::allocator<std::pair<int const, caspar::core::layer_frame> > >, caspar::core::stage::impl::operator()(caspar::core::video_format_desc const&, int, std::vector<int, std::allocator<int> >&)::{lambda()#1}&>(std::__invoke_other, caspar::core::stage::impl::operator()(caspar::core::video_format_desc const&, int, std::vector<int, std::allocator<int> >&)::{lambda()#1}&) (__f=...) at /usr/include/c++/7/bits/invoke.h:60
#9  0x0000556a81bfe6c0 in std::__invoke<caspar::core::stage::impl::operator()(caspar::core::video_format_desc const&, int, std::vector<int, std::allocator<int> >&)::{lambda()#1}&>(std::__invoke_result&&, (caspar::core::stage::impl::operator()(caspar::core::video_format_desc const&, int, std::vector<int, std::allocator<int> >&)::{lambda()#1}&)...) (__fn=...) at /usr/include/c++/7/bits/invoke.h:96
#10 0x0000556a81bfe6c0 in std::__future_base::_Task_state<caspar::core::stage::impl::operator()(caspar::core::video_format_desc const&, int, std::vector<int, std::allocator<int> >&)::{lambda()#1}, std::allocator<int>, std::map<int, caspar::core::layer_frame, std::less<int>, std::allocator<std::pair<int const, std::map> > > ()>::_M_run()::{lambda()#1}::operator()() const (__closure=<optimized out>) at /usr/include/c++/7/future:1421
#11 0x0000556a81bfe6c0 in std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<std::map<int, caspar::core::layer_frame, std::less<int>, std::allocator<std::pair<int const, caspar::core::layer_frame> > > >, std::__future_base::_Result_base::_Deleter>, std::__future_base::_Task_state<caspar::core::stage::impl::operator()(caspar::core::video_format_desc const&, int, std::vector<int, std::allocator<int> >&)::{lambda()#1}, std::allocator<int>, std::map<int, caspar::core::layer_frame, std::less<int>, std::allocator<std::pair<int const, caspar::core::layer_frame> > > ()>::_M_run()::{lambda()#1}, std::map<int, caspar::core::layer_frame, std::less<int>, std::allocator<std::pair<int const, caspar::core::layer_frame> > > >::operator()() const (this=0x7f881b48f930) at /usr/include/c++/7/future:1339
#12 0x0000556a81bfe6c0 in std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<std::map<int, caspar::core::layer_frame, std::less<int>, std::allocator<std::pair<int const, caspar::core::layer_frame> > > >, std::__future_base::_Result_base::_Deleter>, std::__future_base::_Task_state<caspar::core::stage::impl::operator()(caspar::core::video_format_desc const&, int, std::vector<int, std::allocator<int> >&)::{lambda()#1}, std::allocator<int>, std::map<int, caspar::core::layer_frame, std::less<int>, std::allocator<std::pair<int const, caspar::core::layer_frame> > > ()>::_M_run()::{lambda()#1}, std::map<int, caspar::core::layer_frame, std::less<int>, std::allocator<std::pair<int const, caspar::core::layer_frame> > > > >::_M_invoke(std::_Any_data const&) (__functor=...)
    at /usr/include/c++/7/bits/std_function.h:302
#13 0x0000556a81b46399 in std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>::operator()() const (this=<optimized out>) at /usr/include/c++/7/bits/std_function.h:706
#14 0x0000556a81b46399 in std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*) (this=0x7f88214ddfb0, __f=<optimized out>, __did_set=0x7f881b48f8a7) at /usr/include/c++/7/future:561
#15 0x00007f885fc99827 in __pthread_once_slow (once_control=0x7f88214ddfc8, init_routine=0x7f8857ab4760 <__once_proxy>) at pthread_once.c:116
#16 0x0000556a81bf0534 in __gthread_once (__func=<optimized out>, __once=0x7f88214ddfc8) at /usr/include/x86_64-linux-gnu/c++/7/bits/gthr-default.h:699
#17 0x0000556a81bf0534 in std::call_once<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*>(std::once_flag&, void (std::__future_base::_State_baseV2::*&&)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*&&, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*&&, bool*&&) (__f=
    @0x7f881b48f8c0: (void (std::__future_base::_State_baseV2::*)(std::__future_base::_State_baseV2 * const, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter>()> *, bool *)) 0x556a81b46370 <std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)>, __once=...) at /usr/include/c++/7/mutex:684
#18 0x0000556a81bf0534 in std::__future_base::_State_baseV2::_M_set_result(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>, bool) (this=0x7f88214ddfb0, __res=..., __ignore_failure=false) at /usr/include/c++/7/future:401
#19 0x0000556a81bf50a5 in std::__future_base::_Task_state<caspar::core::stage::impl::operator()(caspar::core::video_format_desc const&, int, std::vector<int, std::allocator<int> >&)::{lambda()#1}, std::allocator<int>, std::map<int, caspar::core::layer_frame, std::less<int>, std::allocator<std::pair<int const, std::map> > > ()>::_M_run() (this=<optimized out>) at /usr/include/c++/7/future:1423
#20 0x0000556a81bf50a5 in std::packaged_task<std::map<int, caspar::core::layer_frame, std::less<int>, std::allocator<std::pair<int const, caspar::core::layer_frame> > > ()>::operator()() (this=<optimized out>) at /usr/include/c++/7/future:1556
#21 0x0000556a81bf50a5 in auto caspar::executor::begin_invoke<caspar::core::stage::impl::operator()(caspar::core::video_format_desc const&, int, std::vector<int, std::allocator<int> >&)::{lambda()#1}>(caspar::core::stage::impl::operator()(caspar::core::video_format_desc const&, int, std::vector<int, std::allocator<int> >&)::{lambda()#1}&&)::{lambda()#1}::operator()() (__closure=<optimized out>) at /home/salto/code/casparcg-server-master/src/core/../common/executor.h:73
#22 0x0000556a81bf50a5 in std::_Function_handler<void (), auto caspar::executor::begin_invoke<caspar::core::stage::impl::operator()(caspar::core::video_format_desc const&, int, std::vector<int, std::allocator<int> >&)::{lambda()#1}>(caspar::core::stage::impl::operator()(caspar::core::video_format_desc const&, int, std::vector<int, std::allocator<int> >&)::{lambda()#1}&&)::{lambda()#1}>::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/7/bits/std_function.h:316
#23 0x0000556a81bda72f in std::function<void ()>::operator()() const (this=0x7f881b48f9d0) at /usr/include/c++/7/bits/std_function.h:706
#24 0x0000556a81bda72f in caspar::executor::run() (this=0x7f882861b5a0) at /home/salto/code/casparcg-server-master/src/core/../common/executor.h:142
#25 0x00007f8857ab557f in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#26 0x00007f885fc916db in start_thread (arg=0x7f881b490700) at pthread_create.c:463
#27 0x00007f885751088f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by Julusian** [comment] 2019-11-13 10:32
@saltomodules I spent a bit of time looking into this last week and believe I found the cause. Could you retest to confirm? 66b3508d5469d95af0bfb1e2c95d2e6f22914f09

**Comment by Julusian** [comment] 2020-02-24 11:13
Any update on this? It sounds like it could be resolved now?

**Comment by saltomodules** [comment] 2020-03-13 11:03
Yes, this has been resolved. Our 2.3 server has been humming along nicely for a while now. Thanks!

**Closed** 2020-03-13 11:10 UTC
Labels: bug
