### ISSUE TITLE
Support new video modes 2160p50 and 2160p60

### ISSUE THREAD

**Issue by AurelienRevault** [CasparCG/server#406] opened 2016-01-04 11:04 UTC
The new Decklink 4K Extrem 12G offers UHD at 50p and 60p. But those modes are not yet supported by Caspar. It would be good to supoprt those 2 video modes as they are becoming the broadcasting standards.

**Comment by AurelienRevault** [comment] 2016-01-07 14:19
I just did the modifications. How shall I submit them?

**Comment by mauricev78** [comment] 2016-01-07 14:21
Cool very appreciated please let somebody merge this !!

**Comment by AurelienRevault** [comment] 2016-01-07 14:46
By the way, for graphics an host flash templates has to be generated for the 3 new video modes:
2160p50, 2160p5994 and 2160p60.

for testing I have renamed the existing fth 2160p25 to 2160p50 and it works. But not sure this is clean.

FTh sources are not on github. So a core developper has to do it.

**Comment by ronag** [comment] 2016-01-07 15:27
@AurelienRevault: Jesper Staerker can help you with that.

**Comment by HellGore** [comment] 2016-01-07 15:43
Actually the sources are here: https://github.com/CasparCG/Framework/tree/master/as3/TemplateHost/trunk so they are on github.

**Comment by AurelienRevault** [comment] 2016-01-08 08:35
Oh that's great. Many thanks. My template "expert" will have a look at them then. If we feel comfortable in creating the missing ones, I'll submit a pull request.

**Comment by AurelienRevault** [comment] 2016-01-14 09:00
Host template is done.

I haven't submit a pull request yet because I have the following 2 issues:
- at startup, Caspar can successfully initialize the Decklink in 2160p50, but there is warning saying that the video mode is not supported. Looking at the code, device->DoesSupportVideoMode fails with 2160p50 and  8bitBGRA. However, caspar is working properly
- We also found that audio is very bad in 2160p50 if you start caspar when the decklink is not configured in NTSC before. for now, we put an ugly workaround in dekclink consumer initialization, we first configure it in NTSC and then switch to the video mode configured in caspar.config...

any thoughts?

**Comment by HellGore** [comment] 2016-01-14 09:35
`DoesSupportVideoMode()` seems to be a little bit buggy. For example it returns "not supported" with a Decklink Quad at 720p50 with BGRA, when it really should return "supported with conversion", so I think it is fine to let it warn about not supporting that video mode.

Why does setting it to NTSC before 2160p50 help? Can you explain more about that point?

**Comment by AurelienRevault** [comment] 2016-01-14 09:52
On the last point, we don't know yet exactly why resetting to NTSC before configuring the decklink to 2160p sort the audio issue. We just found that workaround by trial and error... We are not happy with that solution. We think may be something is missing during the initialization process in 2160p... It has probably nothing to with NTSC... 

Maybe the framerate is not correctly set if the initial decklink setting is already 2160p... another company developping a software based on the same board, told they've sort the issue switching their software from 10bit to 8bit... But you don't (and can't) have more details on this.

**Comment by HellGore** [comment] 2016-01-14 11:17
Maybe it is an issue about too few audio samples being scheduled. You could try giving `audio_frame_buffer_` a capacity of 2.

**Comment by AurelienRevault** [comment] 2016-01-14 15:10
setting audio_frame_buffer to 2 is not changing anything (I also tried 4: same result). However, changing video_frame_buffer from 1 to 2, results in much better audio, but then we lose audio/video sync.

**Comment by aruanoc** [comment] 2016-05-26 22:07
Hi Aurelien,

I made a custom build to support 2160p5994 but I'm seeing some issues when I connect a decklink card to a SDI monitor. Is your code online to take a look at (here is mine -> https://github.com/aruanoc/Server/commit/5a3f6315ddd74ef13c69069498dcfe034f4ca80a)? Did you get to use casparCG with 2160p5000 successfully?

I'm also having some issues with the 4K Extreme 12G not outputting the key/alpha channel through the B out SDI port. Did you run into this?

Thank you!

**Comment by AurelienRevault** [comment] 2016-05-27 08:59
Hi,

Yes i managed to have casparcf work in 2160p5000.

Concerning the alpha output, I don’t remember having testing it. But not surprised.

My code is not online yet, I had to switch to another project. I ‘ll try to do some cleanup on Monday an post it on my github.

Cheers
Aurélien

**Comment by AurelienRevault** [comment] 2016-05-31 13:05
please find my modifications here : [https://github.com/AurelienRevault/Caspar-Server/commit/03eba4685a4af40e58652fc54785c2d565f0cd7f](url)

**Comment by aruanoc** [comment] 2016-05-31 17:24
Aurelien,

Thank you very much! Your link wasn't working but I found your commit:

https://github.com/AurelienRevault/Caspar-Server/commit/03eba4685a4af40e58652fc54785c2d565f0cd7f

I'm not seeing the audio issues you were experiencing, at least using system audio. Was that an issue with embedded audio?

Regarding the issues with the key using the 4K Extreme 12G, it turns out it was because we were using a cable that didn't have enough bandwidth and couldn't handle 2160p5994. If someone else runs into this, we had a successful test using a Belden 1694A 4.5Ghz SDI cable.

**Comment by AurelienRevault** [comment] 2016-06-01 08:57
Thanks for the corrected link.

Yes, Audio issue with embedded audio. We never use system audio in production.

**Comment by joaoportela** [comment] 2017-01-25 18:26
Hi!

Has anyone had any progress on this? 

What needs to be done to support 2160p6000 correctly an merge this to the main branch?

**Comment by aruanoc** [comment] 2017-01-25 18:34
Hi Joao,

I have my own fork where I added support to 2160p5000, 2160p5994 and 2160p6000 (in both 2.1.0 and 2.0.7). Tested and working.

https://github.com/aruanoc/CasparCG-Server

**Comment by HellGore** [comment] 2017-01-26 10:13
The thing that I don't like is the workaround with going to NTSC and back. Otherwise I would have merged a long time ago. Is the workaround still needed with newer drivers? I have no hardware to test this properly on.

**Comment by joaoportela** [comment] 2017-01-26 13:07
I see no workaround in @aruanoc branch.

Maybe it doesn't have those issues with the more recent drivers?

**Comment by aruanoc** [comment] 2017-01-26 13:28
I didn't add the workaround programmatically to avoid future conflicts with future merges. However, we use blackmagic 4K Pros and I can confirm that we do need to have the card set to NTSC when windows boots up and then let caspar reset it to the right video mode on start. Otherwise, we have the issue described by Aurien.

That said, I never got to succesfully upgrade the blackmagic API on 2.0.7 and I haven't tested embedded sound on 2.1.0. So I'm not sure if more recent drivers do the trick.

**Comment by HellGore** [comment] 2017-01-26 13:38
@aruanoc Make a pull from your branch and I will merge it if it contains no merge conflicts.

**Comment by joaoportela** [comment] 2017-01-27 15:07
I have compiled @aruanoc branch but I have encountered some performance issues. It seems that, for some reason, the machine cannot handle sending the video at 2160p6000. The video stutters a lot. Trying to fix this by increasing the buffer-depth removes the stutter but makes it run at a non-constant speed (fast-slow-fast-slow-fast-slow).

I don't think it's an hardware issue, since I managed to run this on a machine with the following specs:
Decklink 4k Pro, Intel i76700@3.4Ghz, Windows 10 64bit, NVIDIA GTX 980TI

Do you guys think there needs to be more changes to fix this?

**Comment by HellGore** [comment] 2017-01-27 16:37
> I don't think it's an hardware issue, since I managed to run this on a machine with the following specs:
Decklink 4k Pro, Intel i7-6700 @3.4Ghz, Windows 10 64bit, NVIDIA GTX 980TI

Why couldn't it be a performance problem? What are the specs of the machine that you **have** problems on?

**Comment by aruanoc** [comment] 2017-01-27 16:46
@HellGore I'll look into that next week.

@joaoportela Are you testing on 2.0.7 or 2.1? Our application runs smoothly in 2160p5994 in 2.0.7, but it does run slow(er) in 2.1 out of the box. We haven't spent much time looking into the performance issues in 2.1 using 4K because we use 2.0.7 in production and it's stable.

Also, we also tested the system with NVIDIA GTXs and we ending up using NVIDIA Quadros because their architecture gave us much better performance. We use an NVIDIA Quadro M4000, which is enough for us, but there are far better (and more expensive) Quadros as well.

**Comment by joaoportela** [comment] 2017-01-27 19:23
@HellGore Sorry, the way that I worded that was ambiguous.

It *didn't* work in the machine with those specs (Decklink 4k Pro, Intel i7-6700 @3.4Ghz, Windows 10 64bit, NVIDIA GTX 980TI). And I expected those specs to be enough.

@aruanoc I compiled the 2.1 branch from your repo. I will cherry pick your changes to 2.0.7 and report back.

**Comment by HellGore** [comment] 2017-01-30 10:13
@joaoportela ok, that processor only has 16 PCI Express lanes and the Nvidia needs all of them, so I guess there is some kind of bandwidth sharing going on since you have a Decklink requiring 8 PCI Express lanes in addition summing upp to 24 lanes.

**Comment by HellGore** [comment] 2017-01-30 10:14
Try to use the HD graphics and run without the Nvidia alltogether, then it might actuallyt work better.

**Comment by joaoportela** [comment] 2017-01-30 18:09
@aruanoc I compiled your master branch (2.0.7). Same results.

@HellGore I'll check if it's a PCI lanes issue.
It'll be harder to test the HD graphics card because the motherboard I'm using doesn't have the monitor output.

I'm still suspicious if the PCI lanes really are an issue since DaVinci Resolve seems to be able to output a proper 2160p60 video signal (although it is upscaling a 720p60 video).

Will report back with more info soon. :)

**Comment by aruanoc** [comment] 2017-01-31 19:13
@joaoportela, @HellGore made a good point. We've also had bandwidth issues due to lack of PCI lanes.

@HellGore, I've created the pull requests for both master and 2.1.0. Before doing so, I reverted some changes that I had made to my branch for local compilation and they look clean.

**Comment by joaoportela** [comment] 2017-02-03 15:12
I didn't expect it to be the PCI lanes issue because the card is running at PCIe 2.0 4X, which gives us 2 GB/s bandwidth (=16 Gbps) and 12G-SDI only needs 12Gbps.

But, just to be sure I've tested with a different PCI configuration:
-  Switched the graphics card to the 4x slot (making it 4x gen3) and the DeckLink card to the 16x slot (making it 16x gen2 with a maximum theoretical speed of 64 Gbps). **Same results.**

**Comment by HellGore** [comment] 2017-02-06 12:51
Well the Decklink Card is specified to **require** 8x so I guess it does:

https://www.blackmagicdesign.com/products/decklink/techspecs/W-DLK-26

My guess is that when your system only has the Nvidia card seated it gets the full 16x 3.0 bandwidth. When you also seat the 4K Pro the Nvidia card should get 8x 3.0 bandwidth and the 4K Pro will get its required 8x 2.0 bandwidth.

I think for most purposes 8x PCIe 3.0 should suffice for the Nvidia card but I don't know. You really should have a 2011-v3 system with 40 PCIe 3.0 lanes to be sure.

**Comment by HellGore** [comment] 2017-02-06 13:00
Also it is fully logical that the 4K Pro requires more bandwidth internally than what the SDI signal requires because of every frame being transferred in 8bit BGRA format to the card, which results in about 16Gbit/s instead of 12Gbit/s in 2160p60.

**Comment by joaoportela** [comment] 2017-02-07 11:49
DeckLink card does require a 8x slot; but not necessarily 8x speed (my guess is that it has a physical 8x slot to still have the necessary bandwidth when connecting to gen1 PCIe) hence the testing.

Before the previous post, I confirmed with HWiNFO that everything was working with the expected PCIe speeds:
- Initial setup
-- Graphics card 16x Gen3
-- DeckLink card 4x Gen2
- Switched around
-- Graphics card 4x Gen3 (which has 3.938 GB/s or 31.504 Gbps) - more than enough for what is was doing.
-- DeckLink card 8x Gen2 (which has 4GB/s or 32 Gbps)

The reason I switched the graphics card with the DeckLink card was to be really sure it wasn't a bandwidth issue. Both configurations worked fine* with DaVinci Resolve, which leads me to believe that this is a different issue entirely.

* **fine**: As previously mentioned it's not 100% fine. DaVinci resolve does send a 2160p60 signal correctly but only from 1080p60 videos, it won't work if the source video actually is 2160p60. (note: Caspar does not work even if I try to use 720p60 videos to send a 2160p60 signal).

**Comment by HellGore** [comment] 2017-02-07 13:01
I am pretty sure that the 4K Pro **needs** the 8x PCIe 2.0 bandwidth to support above 30fps in 2160p. Nothing indicates that it is not needed. It is true that the PCIe spec requires all expansion cards to "work" with lower bandwidth, but "work" here does not mean "not having any performance problem".

> "more than enough for what is was doing"

How is it more than enough? CasparCG differs from advanced gaming graphics in that games usually upload/download textures very seldom, but CasparCG does it every frame. This means that applications such as CasparCG are the **most** sensitive ones to PCIe bandwidth. The OpenGL commands themselves doesn't require much bandwidth, it is the texture uploads/downloads that do.

> * Initial setup
> -- Graphics card 16x Gen3
> -- DeckLink card 4x Gen2

To me this indicates that the Decklink is supported by the PCH lanes (not directly connected to the CPU) which could be the problem, because they are shared with USB ports, SATA controllers etc. So maybe the card gets the equivalent bandwidth of 3x or something, much less the needed 8x.

**Comment by premultiply** [comment] 2018-03-01 11:27
Is this fixed/supported in 2.2?

**Comment by ronag** [comment] 2018-03-01 11:30
@premultiply nope, but it's easy to add

**Comment by TomKaltz** [comment] 2018-03-08 14:18
So can someone submit a PR to add these formats?

**Comment by Julusian** [comment] 2018-03-08 14:30
They look to already exist in video_format.cpp. Changelog suggests they have been there since 2.1 beta 2

**Comment by TomKaltz** [comment] 2018-03-08 15:30
I'm going to close this.  OP can re-open if needed.

**Comment by premultiply** [comment] 2018-05-28 08:34
UHD 2160p5000, 2160p5994, 2160p6000: Decklink 4K Pro output mode gets initialized correctly but does not play any content (producers) on current server 2.2 build. "Half framerate" 23.98/24/25/29.97/30p UHD modes are fine.

4K modes (dci2160p2398, dci2160p2400, dci2160p2500) do not work at all (server 2.2 claims about casparcg.config XMLerrors).

**Comment by Julusian** [comment] 2024-03-19 17:09
The dci modes are now defined.

The issues with 2160p50 and above are better described by #1367, closing in favor of that

**Closed by Julusian** 2024-03-19 17:09 UTC
Labels: type/bug, decklink-producer, feedback/pull request wanted
