### ISSUE TITLE
Doesn't cleanup producer with non-responding input

### ISSUE THREAD

**Issue by ronag** [CasparCG/server#1252] opened 2020-03-03 16:04 UTC
Play a HTTP or RTMP stream that connects properly but does not feed any data, run `CLEAR 1`, the producer should be unloaded, but it's stuck forever (see DIAG).

**Comment by ducthiem90** [comment] 2020-04-20 07:36
#1277

**Comment by Julusian** [comment] 2020-04-27 11:13
Duplicate of https://github.com/CasparCG/server/issues/1277

**Closed by Julusian** 2020-04-27 11:13 UTC
Labels: ffmpeg-producer, type/bug
