### ISSUE TITLE
COMMIT COMMAND NOT CLEAR DEFER COMMAND

### ISSUE THREAD

**Issue by DogLorenzo** [CasparCG/server#1503] opened 2023-11-01 11:32 UTC
After I execute a COMMIT command for execute more animations, i have the same animations again if i resend COMMIT command.

The command doesn't clear the DEFER in the animations executed.

**Comment by Julusian** [comment] 2023-11-01 16:56
This is fixed in the next build of master 7cbc4a4

**Closed by Julusian** 2023-11-01 16:56 UTC

**Comment by fillandkey** [comment] 2023-11-07 16:50
Hi, Julusian.
I tried the new build but the issue is still present
