### ISSUE TITLE
Version 2.2 audio out of sync

### ISSUE THREAD

**Issue by Xeing** [CasparCG/server#1170] opened 2019-01-22 19:45 UTC
I have found synchronization failures when trying to play several files with versions 2.2 and 2.3 that however in version 2.1 work correctly.

This file is an example:
https://www.dropbox.com/s/uf6d4ld9m1zsbq5/avst.mp4?dl=0

### Environment
Server version:
2.2.0 66a9e3e Stable
Operating system:
Win 10 x64
Graphics driver:
Nvidia 417.35 (for GTX1050)
Decklink drivers:
none

**Comment by Julusian** [comment] 2019-01-22 20:55
Is this a problem with all files/sources, or only a couple of files you have?

**Comment by Xeing** [comment] 2019-01-24 13:10
I have tried several videos and it seems that:

1. In all videos the audio and video do not start at the same time and there is a small lag.

2. If the samplerate of the file is 44100, it plays at 48000, so after a few seconds the sound is completely out of phase.

**Comment by m0vse** [comment] 2019-02-14 10:21
I can confirm that I am seeing the same effect, playing a long (90 minute) MP4 file (25fps with 44.1Khz audio) the audio was massively out of sync almost from the start and got progressively worse. This same video played perfectly in 2,07 and 2.1. I used Handbrake to re-encode the audio to 48K and the sync problems are gone, so this is a suitable workaround for now but something has definitely changed.

**Comment by m0vse** [comment] 2019-02-14 13:46
This was using a Decklink 4K Extreme with the latest BMD drivers.

**Comment by WuGGu** [comment] 2019-04-11 06:29
Hi everyone, same problem also with the file of @Xeing. async playback of mp4 files.

CasparCG 2.2.0 Stable
Windows 10
BMD Decklink Duo 
Decklink Drivers: 11.1 newest

**Comment by ryci-us** [comment] 2019-06-06 13:54
looks like a bug is in https://github.com/CasparCG/server/blob/bfe314ea5d09762962690a0e39038d777717e18c/src/modules/ffmpeg/producer/av_producer.cpp#L226-L230

From ffmpeg-filters manual 7.37 asetrate - Set the sample rate without altering the PCM data. This will result in a change of speed and pitch.

**Comment by ryci-us** [comment] 2019-06-07 13:49
I have tested with 2.3.0 https://github.com/CasparCG/server/commit/5fadfc858a797a25a1adf502dc8eb23be45372b4 and can confirm that everything is fixed.
This issue can be closed.

**Comment by premultiply** [comment] 2019-06-07 15:02
https://github.com/CasparCG/server/pull/1215#discussion_r291501178

**Comment by abmkrishnan** [comment] 2019-10-26 14:09
Is there any workaround without modifying the source code to play correctly?

**Comment by ryci-us** [comment] 2019-10-27 10:54
Can you give example to reproduce it?

**Comment by toresbe** [comment] 2019-11-02 20:27
This will retain sync (there might be a lip flap issue with the source material, but at least the delay is constant):

`PLAY 1-150 "https://upload.frikanalen.no/media/625334/theora/SirKenRobinson_2010.ogv"`

Here it will go very badly:

`PLAY 1-150 "https://upload.frikanalen.no/media/625334/theora/SirKenRobinson_2010.ogv" SEEK 1500`

**Comment by abmkrishnan** [comment] 2019-12-01 06:34
any update?

**Comment by Julusian** [comment] 2020-03-03 13:46
This is fine when not seeking, the seek portion of this is a duplicate of https://github.com/CasparCG/server/issues/1239

**Closed by Julusian** 2020-03-03 13:46 UTC
